/* CaptureDocklet.c generated by valac 0.34.4, the Vala compiler
 * generated from CaptureDocklet.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <plank.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define CAPTURE_TYPE_CAPTURE_DOCKLET (capture_capture_docklet_get_type ())
#define CAPTURE_CAPTURE_DOCKLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_CAPTURE_DOCKLET, CaptureCaptureDocklet))
#define CAPTURE_CAPTURE_DOCKLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_CAPTURE_DOCKLET, CaptureCaptureDockletClass))
#define CAPTURE_IS_CAPTURE_DOCKLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_CAPTURE_DOCKLET))
#define CAPTURE_IS_CAPTURE_DOCKLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_CAPTURE_DOCKLET))
#define CAPTURE_CAPTURE_DOCKLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_CAPTURE_DOCKLET, CaptureCaptureDockletClass))

typedef struct _CaptureCaptureDocklet CaptureCaptureDocklet;
typedef struct _CaptureCaptureDockletClass CaptureCaptureDockletClass;
typedef struct _CaptureCaptureDockletPrivate CaptureCaptureDockletPrivate;

#define CAPTURE_TYPE_CAPTURE_DOCK_ITEM (capture_capture_dock_item_get_type ())
#define CAPTURE_CAPTURE_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_CAPTURE_DOCK_ITEM, CaptureCaptureDockItem))
#define CAPTURE_CAPTURE_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_CAPTURE_DOCK_ITEM, CaptureCaptureDockItemClass))
#define CAPTURE_IS_CAPTURE_DOCK_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_CAPTURE_DOCK_ITEM))
#define CAPTURE_IS_CAPTURE_DOCK_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_CAPTURE_DOCK_ITEM))
#define CAPTURE_CAPTURE_DOCK_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_CAPTURE_DOCK_ITEM, CaptureCaptureDockItemClass))

typedef struct _CaptureCaptureDockItem CaptureCaptureDockItem;
typedef struct _CaptureCaptureDockItemClass CaptureCaptureDockItemClass;

struct _CaptureCaptureDocklet {
	GObject parent_instance;
	CaptureCaptureDockletPrivate * priv;
};

struct _CaptureCaptureDockletClass {
	GObjectClass parent_class;
};


static gpointer capture_capture_docklet_parent_class = NULL;
static PlankDockletIface* capture_capture_docklet_plank_docklet_parent_iface = NULL;

void docklet_init (PlankDockletManager* manager);
GType capture_capture_docklet_get_type (void) G_GNUC_CONST;
#define CAPTURE_G_RESOURCE_PATH "/de/hannenz/capture"
enum  {
	CAPTURE_CAPTURE_DOCKLET_DUMMY_PROPERTY
};
static const gchar* capture_capture_docklet_real_get_id (PlankDocklet* base);
static const gchar* capture_capture_docklet_real_get_name (PlankDocklet* base);
static const gchar* capture_capture_docklet_real_get_description (PlankDocklet* base);
static const gchar* capture_capture_docklet_real_get_icon (PlankDocklet* base);
static gboolean capture_capture_docklet_real_is_supported (PlankDocklet* base);
static PlankDockElement* capture_capture_docklet_real_make_element (PlankDocklet* base, const gchar* launcher, GFile* file);
CaptureCaptureDockItem* capture_capture_dock_item_new_with_dockitem_file (GFile* file);
CaptureCaptureDockItem* capture_capture_dock_item_construct_with_dockitem_file (GType object_type, GFile* file);
GType capture_capture_dock_item_get_type (void) G_GNUC_CONST;
CaptureCaptureDocklet* capture_capture_docklet_new (void);
CaptureCaptureDocklet* capture_capture_docklet_construct (GType object_type);


void docklet_init (PlankDockletManager* manager) {
	PlankDockletManager* _tmp0_ = NULL;
	g_return_if_fail (manager != NULL);
	_tmp0_ = manager;
	plank_docklet_manager_register_docklet (_tmp0_, CAPTURE_TYPE_CAPTURE_DOCKLET);
}


static const gchar* capture_capture_docklet_real_get_id (PlankDocklet* base) {
	CaptureCaptureDocklet * self;
	const gchar* result = NULL;
	self = (CaptureCaptureDocklet*) base;
	result = "capture";
	return result;
}


static const gchar* capture_capture_docklet_real_get_name (PlankDocklet* base) {
	CaptureCaptureDocklet * self;
	const gchar* result = NULL;
	self = (CaptureCaptureDocklet*) base;
	result = "Capture";
	return result;
}


static const gchar* capture_capture_docklet_real_get_description (PlankDocklet* base) {
	CaptureCaptureDocklet * self;
	const gchar* result = NULL;
	self = (CaptureCaptureDocklet*) base;
	result = "Screen capture and screenshot docklet";
	return result;
}


static const gchar* capture_capture_docklet_real_get_icon (PlankDocklet* base) {
	CaptureCaptureDocklet * self;
	const gchar* result = NULL;
	self = (CaptureCaptureDocklet*) base;
	result = "camera-video";
	return result;
}


static gboolean capture_capture_docklet_real_is_supported (PlankDocklet* base) {
	CaptureCaptureDocklet * self;
	gboolean result = FALSE;
	self = (CaptureCaptureDocklet*) base;
	result = FALSE;
	return result;
}


static PlankDockElement* capture_capture_docklet_real_make_element (PlankDocklet* base, const gchar* launcher, GFile* file) {
	CaptureCaptureDocklet * self;
	PlankDockElement* result = NULL;
	GFile* _tmp0_ = NULL;
	CaptureCaptureDockItem* _tmp1_ = NULL;
	self = (CaptureCaptureDocklet*) base;
	g_return_val_if_fail (launcher != NULL, NULL);
	g_return_val_if_fail (file != NULL, NULL);
	_tmp0_ = file;
	_tmp1_ = capture_capture_dock_item_new_with_dockitem_file (_tmp0_);
	result = (PlankDockElement*) _tmp1_;
	return result;
}


CaptureCaptureDocklet* capture_capture_docklet_construct (GType object_type) {
	CaptureCaptureDocklet * self = NULL;
	self = (CaptureCaptureDocklet*) g_object_new (object_type, NULL);
	return self;
}


CaptureCaptureDocklet* capture_capture_docklet_new (void) {
	return capture_capture_docklet_construct (CAPTURE_TYPE_CAPTURE_DOCKLET);
}


static void capture_capture_docklet_class_init (CaptureCaptureDockletClass * klass) {
	capture_capture_docklet_parent_class = g_type_class_peek_parent (klass);
}


static void capture_capture_docklet_plank_docklet_interface_init (PlankDockletIface * iface) {
	capture_capture_docklet_plank_docklet_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_id = (const gchar* (*)(PlankDocklet*)) capture_capture_docklet_real_get_id;
	iface->get_name = (const gchar* (*)(PlankDocklet*)) capture_capture_docklet_real_get_name;
	iface->get_description = (const gchar* (*)(PlankDocklet*)) capture_capture_docklet_real_get_description;
	iface->get_icon = (const gchar* (*)(PlankDocklet*)) capture_capture_docklet_real_get_icon;
	iface->is_supported = (gboolean (*)(PlankDocklet*)) capture_capture_docklet_real_is_supported;
	iface->make_element = (PlankDockElement* (*)(PlankDocklet*, const gchar*, GFile*)) capture_capture_docklet_real_make_element;
}


static void capture_capture_docklet_instance_init (CaptureCaptureDocklet * self) {
}


GType capture_capture_docklet_get_type (void) {
	static volatile gsize capture_capture_docklet_type_id__volatile = 0;
	if (g_once_init_enter (&capture_capture_docklet_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CaptureCaptureDockletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) capture_capture_docklet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaptureCaptureDocklet), 0, (GInstanceInitFunc) capture_capture_docklet_instance_init, NULL };
		static const GInterfaceInfo plank_docklet_info = { (GInterfaceInitFunc) capture_capture_docklet_plank_docklet_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType capture_capture_docklet_type_id;
		capture_capture_docklet_type_id = g_type_register_static (G_TYPE_OBJECT, "CaptureCaptureDocklet", &g_define_type_info, 0);
		g_type_add_interface_static (capture_capture_docklet_type_id, PLANK_TYPE_DOCKLET, &plank_docklet_info);
		g_once_init_leave (&capture_capture_docklet_type_id__volatile, capture_capture_docklet_type_id);
	}
	return capture_capture_docklet_type_id__volatile;
}



