/* CapturePreferences.c generated by valac 0.34.4, the Vala compiler
 * generated from CapturePreferences.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <plank.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define CAPTURE_TYPE_CAPTURE_PREFERENCES (capture_capture_preferences_get_type ())
#define CAPTURE_CAPTURE_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_CAPTURE_PREFERENCES, CaptureCapturePreferences))
#define CAPTURE_CAPTURE_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_CAPTURE_PREFERENCES, CaptureCapturePreferencesClass))
#define CAPTURE_IS_CAPTURE_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_CAPTURE_PREFERENCES))
#define CAPTURE_IS_CAPTURE_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_CAPTURE_PREFERENCES))
#define CAPTURE_CAPTURE_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_CAPTURE_PREFERENCES, CaptureCapturePreferencesClass))

typedef struct _CaptureCapturePreferences CaptureCapturePreferences;
typedef struct _CaptureCapturePreferencesClass CaptureCapturePreferencesClass;
typedef struct _CaptureCapturePreferencesPrivate CaptureCapturePreferencesPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CaptureCapturePreferences {
	PlankDockItemPreferences parent_instance;
	CaptureCapturePreferencesPrivate * priv;
	guint framerate;
	gint countdown;
	gchar* file_format;
	gchar* destination;
	gboolean show_notifications;
	gboolean copy_to_clipboard;
	gboolean auto_save;
	gboolean include_pointer;
};

struct _CaptureCapturePreferencesClass {
	PlankDockItemPreferencesClass parent_class;
};


static gpointer capture_capture_preferences_parent_class = NULL;

GType capture_capture_preferences_get_type (void) G_GNUC_CONST;
enum  {
	CAPTURE_CAPTURE_PREFERENCES_DUMMY_PROPERTY
};
CaptureCapturePreferences* capture_capture_preferences_new_with_file (GFile* file);
CaptureCapturePreferences* capture_capture_preferences_construct_with_file (GType object_type, GFile* file);
static void capture_capture_preferences_real_reset_properties (PlankPreferences* base);
CaptureCapturePreferences* capture_capture_preferences_new (void);
CaptureCapturePreferences* capture_capture_preferences_construct (GType object_type);
static void capture_capture_preferences_finalize (GObject* obj);


CaptureCapturePreferences* capture_capture_preferences_construct_with_file (GType object_type, GFile* file) {
	CaptureCapturePreferences * self = NULL;
	GFile* _tmp0_ = NULL;
	g_return_val_if_fail (file != NULL, NULL);
	_tmp0_ = file;
	self = (CaptureCapturePreferences*) plank_dock_item_preferences_construct_with_file (object_type, _tmp0_);
	return self;
}


CaptureCapturePreferences* capture_capture_preferences_new_with_file (GFile* file) {
	return capture_capture_preferences_construct_with_file (CAPTURE_TYPE_CAPTURE_PREFERENCES, file);
}


static void capture_capture_preferences_real_reset_properties (PlankPreferences* base) {
	CaptureCapturePreferences * self;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	self = (CaptureCapturePreferences*) base;
	self->framerate = (guint) 10;
	self->countdown = 7;
	_tmp0_ = g_strdup ("png");
	_g_free0 (self->file_format);
	self->file_format = _tmp0_;
	_tmp1_ = g_get_home_dir ();
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->destination);
	self->destination = _tmp2_;
	self->show_notifications = TRUE;
	self->copy_to_clipboard = TRUE;
	self->auto_save = TRUE;
	self->include_pointer = TRUE;
}


CaptureCapturePreferences* capture_capture_preferences_construct (GType object_type) {
	CaptureCapturePreferences * self = NULL;
	self = (CaptureCapturePreferences*) plank_dock_item_preferences_construct (object_type);
	return self;
}


CaptureCapturePreferences* capture_capture_preferences_new (void) {
	return capture_capture_preferences_construct (CAPTURE_TYPE_CAPTURE_PREFERENCES);
}


static void capture_capture_preferences_class_init (CaptureCapturePreferencesClass * klass) {
	capture_capture_preferences_parent_class = g_type_class_peek_parent (klass);
	((PlankPreferencesClass *) klass)->reset_properties = capture_capture_preferences_real_reset_properties;
	G_OBJECT_CLASS (klass)->finalize = capture_capture_preferences_finalize;
}


static void capture_capture_preferences_instance_init (CaptureCapturePreferences * self) {
}


static void capture_capture_preferences_finalize (GObject* obj) {
	CaptureCapturePreferences * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CAPTURE_TYPE_CAPTURE_PREFERENCES, CaptureCapturePreferences);
	_g_free0 (self->file_format);
	_g_free0 (self->destination);
	G_OBJECT_CLASS (capture_capture_preferences_parent_class)->finalize (obj);
}


GType capture_capture_preferences_get_type (void) {
	static volatile gsize capture_capture_preferences_type_id__volatile = 0;
	if (g_once_init_enter (&capture_capture_preferences_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CaptureCapturePreferencesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) capture_capture_preferences_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaptureCapturePreferences), 0, (GInstanceInitFunc) capture_capture_preferences_instance_init, NULL };
		GType capture_capture_preferences_type_id;
		capture_capture_preferences_type_id = g_type_register_static (PLANK_TYPE_DOCK_ITEM_PREFERENCES, "CaptureCapturePreferences", &g_define_type_info, 0);
		g_once_init_leave (&capture_capture_preferences_type_id__volatile, capture_capture_preferences_type_id);
	}
	return capture_capture_preferences_type_id__volatile;
}



