/* CapturePreview.c generated by valac 0.34.4, the Vala compiler
 * generated from CapturePreview.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define CAPTURE_TYPE_CAPTURE_PREVIEW (capture_capture_preview_get_type ())
#define CAPTURE_CAPTURE_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_CAPTURE_PREVIEW, CaptureCapturePreview))
#define CAPTURE_CAPTURE_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_CAPTURE_PREVIEW, CaptureCapturePreviewClass))
#define CAPTURE_IS_CAPTURE_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_CAPTURE_PREVIEW))
#define CAPTURE_IS_CAPTURE_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_CAPTURE_PREVIEW))
#define CAPTURE_CAPTURE_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_CAPTURE_PREVIEW, CaptureCapturePreviewClass))

typedef struct _CaptureCapturePreview CaptureCapturePreview;
typedef struct _CaptureCapturePreviewClass CaptureCapturePreviewClass;
typedef struct _CaptureCapturePreviewPrivate CaptureCapturePreviewPrivate;

#define CAPTURE_TYPE_SEQUENCE (capture_sequence_get_type ())
#define CAPTURE_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_SEQUENCE, CaptureSequence))
#define CAPTURE_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_SEQUENCE, CaptureSequenceClass))
#define CAPTURE_IS_SEQUENCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_SEQUENCE))
#define CAPTURE_IS_SEQUENCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_SEQUENCE))
#define CAPTURE_SEQUENCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_SEQUENCE, CaptureSequenceClass))

typedef struct _CaptureSequence CaptureSequence;
typedef struct _CaptureSequenceClass CaptureSequenceClass;
#define _capture_sequence_unref0(var) ((var == NULL) ? NULL : (var = (capture_sequence_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CaptureCapturePreview {
	GtkDialog parent_instance;
	CaptureCapturePreviewPrivate * priv;
	CaptureSequence* sequence;
};

struct _CaptureCapturePreviewClass {
	GtkDialogClass parent_class;
};

struct _CaptureCapturePreviewPrivate {
	guint sequence_length;
	GtkImage* image;
	gboolean playing;
	GtkButton* play_button;
	GtkButton* next_button;
	GtkButton* prev_button;
	GtkProgressBar* progress_bar;
};


static gpointer capture_capture_preview_parent_class = NULL;

GType capture_capture_preview_get_type (void) G_GNUC_CONST;
gpointer capture_sequence_ref (gpointer instance);
void capture_sequence_unref (gpointer instance);
GParamSpec* capture_param_spec_sequence (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void capture_value_set_sequence (GValue* value, gpointer v_object);
void capture_value_take_sequence (GValue* value, gpointer v_object);
gpointer capture_value_get_sequence (const GValue* value);
GType capture_sequence_get_type (void) G_GNUC_CONST;
#define CAPTURE_CAPTURE_PREVIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CAPTURE_TYPE_CAPTURE_PREVIEW, CaptureCapturePreviewPrivate))
enum  {
	CAPTURE_CAPTURE_PREVIEW_DUMMY_PROPERTY
};
CaptureCapturePreview* capture_capture_preview_new (CaptureSequence* sequence);
CaptureCapturePreview* capture_capture_preview_construct (GType object_type, CaptureSequence* sequence);
guint capture_sequence_length (CaptureSequence* self);
GdkPixbuf* capture_sequence_first (CaptureSequence* self);
static void capture_capture_preview_create_widgets (CaptureCapturePreview* self);
static void capture_capture_preview_connect_signals (CaptureCapturePreview* self);
void capture_capture_preview_run_sequence (CaptureCapturePreview* self);
static void capture_capture_preview_on_play_button_clicked (CaptureCapturePreview* self, GtkButton* button);
static void _capture_capture_preview_on_play_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void capture_capture_preview_on_prev_button_clicked (CaptureCapturePreview* self);
static void _capture_capture_preview_on_prev_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void capture_capture_preview_on_next_button_clicked (CaptureCapturePreview* self);
static void _capture_capture_preview_on_next_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
guint capture_sequence_get_framerate (CaptureSequence* self);
static gboolean __lambda27_ (CaptureCapturePreview* self);
GdkPixbuf* capture_sequence_next (CaptureSequence* self);
static void capture_capture_preview_update_progress_bar (CaptureCapturePreview* self);
static gboolean ___lambda27__gsource_func (gpointer self);
GdkPixbuf* capture_sequence_previous (CaptureSequence* self);
guint capture_sequence_get_frame (CaptureSequence* self);
static void capture_capture_preview_finalize (GObject* obj);


static gpointer _capture_sequence_ref0 (gpointer self) {
	return self ? capture_sequence_ref (self) : NULL;
}


CaptureCapturePreview* capture_capture_preview_construct (GType object_type, CaptureSequence* sequence) {
	CaptureCapturePreview * self = NULL;
	CaptureSequence* _tmp0_ = NULL;
	CaptureSequence* _tmp1_ = NULL;
	CaptureSequence* _tmp2_ = NULL;
	guint _tmp3_ = 0U;
	CaptureSequence* _tmp4_ = NULL;
	GdkPixbuf* _tmp5_ = NULL;
	GdkPixbuf* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	CaptureSequence* _tmp9_ = NULL;
	GdkPixbuf* _tmp10_ = NULL;
	GdkPixbuf* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	g_return_val_if_fail (sequence != NULL, NULL);
	self = (CaptureCapturePreview*) g_object_new (object_type, NULL);
	_tmp0_ = sequence;
	_tmp1_ = _capture_sequence_ref0 (_tmp0_);
	_capture_sequence_unref0 (self->sequence);
	self->sequence = _tmp1_;
	_tmp2_ = sequence;
	_tmp3_ = capture_sequence_length (_tmp2_);
	self->priv->sequence_length = _tmp3_;
	gtk_window_set_title ((GtkWindow*) self, "Preview");
	_tmp4_ = sequence;
	_tmp5_ = capture_sequence_first (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = gdk_pixbuf_get_width (_tmp6_);
	_tmp8_ = CLAMP (_tmp7_, 500, 1000);
	_tmp9_ = sequence;
	_tmp10_ = capture_sequence_first (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = gdk_pixbuf_get_height (_tmp11_);
	_tmp13_ = CLAMP (_tmp12_, 400, 800);
	gtk_window_set_default_size ((GtkWindow*) self, _tmp8_, _tmp13_);
	_g_object_unref0 (_tmp11_);
	_g_object_unref0 (_tmp6_);
	capture_capture_preview_create_widgets (self);
	capture_capture_preview_connect_signals (self);
	capture_capture_preview_run_sequence (self);
	return self;
}


CaptureCapturePreview* capture_capture_preview_new (CaptureSequence* sequence) {
	return capture_capture_preview_construct (CAPTURE_TYPE_CAPTURE_PREVIEW, sequence);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void capture_capture_preview_create_widgets (CaptureCapturePreview* self) {
	GtkImage* _tmp0_ = NULL;
	GtkImage* _tmp1_ = NULL;
	CaptureSequence* _tmp2_ = NULL;
	GdkPixbuf* _tmp3_ = NULL;
	GdkPixbuf* _tmp4_ = NULL;
	GtkBox* content_area = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkBox* _tmp6_ = NULL;
	GtkScrolledWindow* swin = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
	GtkImage* _tmp8_ = NULL;
	GtkProgressBar* _tmp9_ = NULL;
	GtkProgressBar* _tmp10_ = NULL;
	GtkProgressBar* _tmp11_ = NULL;
	GtkButtonBox* button_box = NULL;
	GtkButtonBox* _tmp12_ = NULL;
	GtkButton* _tmp13_ = NULL;
	GtkButton* _tmp14_ = NULL;
	GtkButton* _tmp15_ = NULL;
	GtkButton* _tmp16_ = NULL;
	GtkButton* _tmp17_ = NULL;
	GtkButton* _tmp18_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->image);
	self->priv->image = _tmp0_;
	_tmp1_ = self->priv->image;
	_tmp2_ = self->sequence;
	_tmp3_ = capture_sequence_first (_tmp2_);
	_tmp4_ = _tmp3_;
	g_object_set (_tmp1_, "pixbuf", _tmp4_, NULL);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	_tmp6_ = _g_object_ref0 (_tmp5_);
	content_area = _tmp6_;
	_tmp7_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp7_);
	swin = _tmp7_;
	_tmp8_ = self->priv->image;
	gtk_container_add ((GtkContainer*) swin, (GtkWidget*) _tmp8_);
	gtk_box_pack_start (content_area, (GtkWidget*) swin, TRUE, TRUE, (guint) 0);
	_tmp9_ = (GtkProgressBar*) gtk_progress_bar_new ();
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->progress_bar);
	self->priv->progress_bar = _tmp9_;
	_tmp10_ = self->priv->progress_bar;
	gtk_progress_bar_set_show_text (_tmp10_, TRUE);
	_tmp11_ = self->priv->progress_bar;
	gtk_box_pack_start (content_area, (GtkWidget*) _tmp11_, FALSE, FALSE, (guint) 0);
	_tmp12_ = (GtkButtonBox*) gtk_button_box_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp12_);
	button_box = _tmp12_;
	gtk_button_box_set_layout (button_box, GTK_BUTTONBOX_CENTER);
	_tmp13_ = (GtkButton*) gtk_button_new_with_label ("<");
	g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->prev_button);
	self->priv->prev_button = _tmp13_;
	_tmp14_ = self->priv->prev_button;
	gtk_box_pack_start ((GtkBox*) button_box, (GtkWidget*) _tmp14_, TRUE, FALSE, (guint) 0);
	_tmp15_ = (GtkButton*) gtk_button_new_with_label ("Play");
	g_object_ref_sink (_tmp15_);
	_g_object_unref0 (self->priv->play_button);
	self->priv->play_button = _tmp15_;
	_tmp16_ = self->priv->play_button;
	gtk_box_pack_start ((GtkBox*) button_box, (GtkWidget*) _tmp16_, TRUE, FALSE, (guint) 0);
	_tmp17_ = (GtkButton*) gtk_button_new_with_label (">");
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->next_button);
	self->priv->next_button = _tmp17_;
	_tmp18_ = self->priv->next_button;
	gtk_box_pack_start ((GtkBox*) button_box, (GtkWidget*) _tmp18_, TRUE, FALSE, (guint) 0);
	gtk_box_pack_start (content_area, (GtkWidget*) button_box, FALSE, FALSE, (guint) 0);
	gtk_dialog_add_button ((GtkDialog*) self, "Close", (gint) GTK_RESPONSE_CLOSE);
	gtk_dialog_add_button ((GtkDialog*) self, "Save", (gint) GTK_RESPONSE_ACCEPT);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (button_box);
	_g_object_unref0 (swin);
	_g_object_unref0 (content_area);
}


static void _capture_capture_preview_on_play_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	capture_capture_preview_on_play_button_clicked ((CaptureCapturePreview*) self, _sender);
}


static void _capture_capture_preview_on_prev_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	capture_capture_preview_on_prev_button_clicked ((CaptureCapturePreview*) self);
}


static void _capture_capture_preview_on_next_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	capture_capture_preview_on_next_button_clicked ((CaptureCapturePreview*) self);
}


static void capture_capture_preview_connect_signals (CaptureCapturePreview* self) {
	GtkButton* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->play_button;
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) _capture_capture_preview_on_play_button_clicked_gtk_button_clicked, self, 0);
	_tmp1_ = self->priv->prev_button;
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) _capture_capture_preview_on_prev_button_clicked_gtk_button_clicked, self, 0);
	_tmp2_ = self->priv->next_button;
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) _capture_capture_preview_on_next_button_clicked_gtk_button_clicked, self, 0);
}


static gboolean __lambda27_ (CaptureCapturePreview* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = self->priv->playing;
	if (_tmp0_ == TRUE) {
		GtkImage* _tmp1_ = NULL;
		CaptureSequence* _tmp2_ = NULL;
		GdkPixbuf* _tmp3_ = NULL;
		GdkPixbuf* _tmp4_ = NULL;
		_tmp1_ = self->priv->image;
		_tmp2_ = self->sequence;
		_tmp3_ = capture_sequence_next (_tmp2_);
		_tmp4_ = _tmp3_;
		g_object_set (_tmp1_, "pixbuf", _tmp4_, NULL);
		_g_object_unref0 (_tmp4_);
		capture_capture_preview_update_progress_bar (self);
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda27__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda27_ ((CaptureCapturePreview*) self);
	return result;
}


void capture_capture_preview_run_sequence (CaptureCapturePreview* self) {
	CaptureSequence* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->sequence;
	_tmp1_ = capture_sequence_get_framerate (_tmp0_);
	_tmp2_ = _tmp1_;
	g_timeout_add_full (G_PRIORITY_DEFAULT, 1000 / _tmp2_, ___lambda27__gsource_func, g_object_ref (self), g_object_unref);
}


static void capture_capture_preview_on_play_button_clicked (CaptureCapturePreview* self, GtkButton* button) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GtkButton* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	_tmp0_ = self->priv->playing;
	self->priv->playing = !_tmp0_;
	_tmp2_ = self->priv->playing;
	if (_tmp2_) {
		_tmp1_ = "Pause";
	} else {
		_tmp1_ = "Play";
	}
	_tmp3_ = button;
	gtk_button_set_label (_tmp3_, _tmp1_);
}


static void capture_capture_preview_on_prev_button_clicked (CaptureCapturePreview* self) {
	GtkImage* _tmp0_ = NULL;
	CaptureSequence* _tmp1_ = NULL;
	GdkPixbuf* _tmp2_ = NULL;
	GdkPixbuf* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->image;
	_tmp1_ = self->sequence;
	_tmp2_ = capture_sequence_previous (_tmp1_);
	_tmp3_ = _tmp2_;
	g_object_set (_tmp0_, "pixbuf", _tmp3_, NULL);
	_g_object_unref0 (_tmp3_);
	capture_capture_preview_update_progress_bar (self);
}


static void capture_capture_preview_on_next_button_clicked (CaptureCapturePreview* self) {
	GtkImage* _tmp0_ = NULL;
	CaptureSequence* _tmp1_ = NULL;
	GdkPixbuf* _tmp2_ = NULL;
	GdkPixbuf* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->image;
	_tmp1_ = self->sequence;
	_tmp2_ = capture_sequence_next (_tmp1_);
	_tmp3_ = _tmp2_;
	g_object_set (_tmp0_, "pixbuf", _tmp3_, NULL);
	_g_object_unref0 (_tmp3_);
	capture_capture_preview_update_progress_bar (self);
}


static void capture_capture_preview_update_progress_bar (CaptureCapturePreview* self) {
	GtkProgressBar* _tmp0_ = NULL;
	CaptureSequence* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	GtkProgressBar* _tmp5_ = NULL;
	CaptureSequence* _tmp6_ = NULL;
	guint _tmp7_ = 0U;
	guint _tmp8_ = 0U;
	guint _tmp9_ = 0U;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->progress_bar;
	_tmp1_ = self->sequence;
	_tmp2_ = capture_sequence_get_frame (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->priv->sequence_length;
	gtk_progress_bar_set_fraction (_tmp0_, ((gdouble) _tmp3_) / ((gdouble) _tmp4_));
	_tmp5_ = self->priv->progress_bar;
	_tmp6_ = self->sequence;
	_tmp7_ = capture_sequence_get_frame (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = self->priv->sequence_length;
	_tmp10_ = g_strdup_printf ("%u/%u", _tmp8_, _tmp9_);
	_tmp11_ = _tmp10_;
	gtk_progress_bar_set_text (_tmp5_, _tmp11_);
	_g_free0 (_tmp11_);
}


static void capture_capture_preview_class_init (CaptureCapturePreviewClass * klass) {
	capture_capture_preview_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CaptureCapturePreviewPrivate));
	G_OBJECT_CLASS (klass)->finalize = capture_capture_preview_finalize;
}


static void capture_capture_preview_instance_init (CaptureCapturePreview * self) {
	self->priv = CAPTURE_CAPTURE_PREVIEW_GET_PRIVATE (self);
	self->priv->playing = FALSE;
}


static void capture_capture_preview_finalize (GObject* obj) {
	CaptureCapturePreview * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CAPTURE_TYPE_CAPTURE_PREVIEW, CaptureCapturePreview);
	_capture_sequence_unref0 (self->sequence);
	_g_object_unref0 (self->priv->image);
	_g_object_unref0 (self->priv->play_button);
	_g_object_unref0 (self->priv->next_button);
	_g_object_unref0 (self->priv->prev_button);
	_g_object_unref0 (self->priv->progress_bar);
	G_OBJECT_CLASS (capture_capture_preview_parent_class)->finalize (obj);
}


GType capture_capture_preview_get_type (void) {
	static volatile gsize capture_capture_preview_type_id__volatile = 0;
	if (g_once_init_enter (&capture_capture_preview_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CaptureCapturePreviewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) capture_capture_preview_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaptureCapturePreview), 0, (GInstanceInitFunc) capture_capture_preview_instance_init, NULL };
		GType capture_capture_preview_type_id;
		capture_capture_preview_type_id = g_type_register_static (gtk_dialog_get_type (), "CaptureCapturePreview", &g_define_type_info, 0);
		g_once_init_leave (&capture_capture_preview_type_id__volatile, capture_capture_preview_type_id);
	}
	return capture_capture_preview_type_id__volatile;
}



