/* Config.c generated by valac 0.34.4, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CAPTURE_CONSTANTS_DATADIR "/usr/lib/x86_64-linux-gnu/plank/docklets/share"
#define CAPTURE_CONSTANTS_PKGDATADIR "/usr/lib/x86_64-linux-gnu/plank/docklets/share/docklet-capture"
#define CAPTURE_CONSTANTS_GETTEXT_PACKAGE "docklet-capture"
#define CAPTURE_CONSTANTS_RELEASE_NAME "docklet-capture"
#define CAPTURE_CONSTANTS_VERSION "1.0.0"



