/* Countdown.c generated by valac 0.34.4, the Vala compiler
 * generated from Countdown.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define CAPTURE_TYPE_COUNTDOWN (capture_countdown_get_type ())
#define CAPTURE_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_COUNTDOWN, CaptureCountdown))
#define CAPTURE_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_COUNTDOWN, CaptureCountdownClass))
#define CAPTURE_IS_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_COUNTDOWN))
#define CAPTURE_IS_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_COUNTDOWN))
#define CAPTURE_COUNTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_COUNTDOWN, CaptureCountdownClass))

typedef struct _CaptureCountdown CaptureCountdown;
typedef struct _CaptureCountdownClass CaptureCountdownClass;
typedef struct _CaptureCountdownPrivate CaptureCountdownPrivate;
typedef struct _CaptureParamSpecCountdown CaptureParamSpecCountdown;

struct _CaptureCountdown {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CaptureCountdownPrivate * priv;
	gint timer;
};

struct _CaptureCountdownClass {
	GTypeClass parent_class;
	void (*finalize) (CaptureCountdown *self);
};

struct _CaptureCountdownPrivate {
	gint _seconds;
};

struct _CaptureParamSpecCountdown {
	GParamSpec parent_instance;
};


static gpointer capture_countdown_parent_class = NULL;

gpointer capture_countdown_ref (gpointer instance);
void capture_countdown_unref (gpointer instance);
GParamSpec* capture_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void capture_value_set_countdown (GValue* value, gpointer v_object);
void capture_value_take_countdown (GValue* value, gpointer v_object);
gpointer capture_value_get_countdown (const GValue* value);
GType capture_countdown_get_type (void) G_GNUC_CONST;
#define CAPTURE_COUNTDOWN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CAPTURE_TYPE_COUNTDOWN, CaptureCountdownPrivate))
enum  {
	CAPTURE_COUNTDOWN_DUMMY_PROPERTY
};
CaptureCountdown* capture_countdown_new (gint seconds);
CaptureCountdown* capture_countdown_construct (GType object_type, gint seconds);
void capture_countdown_set_seconds (CaptureCountdown* self, gint value);
void capture_countdown_start (CaptureCountdown* self);
gint capture_countdown_get_seconds (CaptureCountdown* self);
static gboolean __lambda23_ (CaptureCountdown* self);
static gboolean ___lambda23__gsource_func (gpointer self);
static void g_cclosure_user_marshal_VOID__INT_DOUBLE (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void capture_countdown_finalize (CaptureCountdown* obj);


CaptureCountdown* capture_countdown_construct (GType object_type, gint seconds) {
	CaptureCountdown* self = NULL;
	gint _tmp0_ = 0;
	self = (CaptureCountdown*) g_type_create_instance (object_type);
	_tmp0_ = seconds;
	capture_countdown_set_seconds (self, _tmp0_);
	return self;
}


CaptureCountdown* capture_countdown_new (gint seconds) {
	return capture_countdown_construct (CAPTURE_TYPE_COUNTDOWN, seconds);
}


static gboolean __lambda23_ (CaptureCountdown* self) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	_tmp0_ = self->timer;
	self->timer = _tmp0_ - 1;
	_tmp1_ = self->timer;
	_tmp2_ = self->priv->_seconds;
	_tmp3_ = self->timer;
	_tmp4_ = self->priv->_seconds;
	g_signal_emit_by_name (self, "tick", _tmp1_, ((gdouble) (_tmp2_ - _tmp3_)) / ((gdouble) _tmp4_));
	_tmp5_ = self->timer;
	if (_tmp5_ <= 0) {
		g_signal_emit_by_name (self, "ignition");
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda23__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda23_ ((CaptureCountdown*) self);
	return result;
}


void capture_countdown_start (CaptureCountdown* self) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_seconds;
	self->timer = _tmp0_;
	_tmp1_ = self->timer;
	if (_tmp1_ == 0) {
		g_signal_emit_by_name (self, "ignition");
		return;
	}
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 1, ___lambda23__gsource_func, capture_countdown_ref (self), capture_countdown_unref);
}


gint capture_countdown_get_seconds (CaptureCountdown* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_seconds;
	result = _tmp0_;
	return result;
}


void capture_countdown_set_seconds (CaptureCountdown* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_seconds = _tmp0_;
}


static void g_cclosure_user_marshal_VOID__INT_DOUBLE (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_DOUBLE) (gpointer data1, gint arg_1, gdouble arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_DOUBLE callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__INT_DOUBLE) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_int (param_values + 1), g_value_get_double (param_values + 2), data2);
}


static void capture_value_countdown_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void capture_value_countdown_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		capture_countdown_unref (value->data[0].v_pointer);
	}
}


static void capture_value_countdown_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = capture_countdown_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer capture_value_countdown_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* capture_value_countdown_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CaptureCountdown* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = capture_countdown_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* capture_value_countdown_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CaptureCountdown** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = capture_countdown_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* capture_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CaptureParamSpecCountdown* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CAPTURE_TYPE_COUNTDOWN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer capture_value_get_countdown (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CAPTURE_TYPE_COUNTDOWN), NULL);
	return value->data[0].v_pointer;
}


void capture_value_set_countdown (GValue* value, gpointer v_object) {
	CaptureCountdown* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CAPTURE_TYPE_COUNTDOWN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CAPTURE_TYPE_COUNTDOWN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		capture_countdown_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		capture_countdown_unref (old);
	}
}


void capture_value_take_countdown (GValue* value, gpointer v_object) {
	CaptureCountdown* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CAPTURE_TYPE_COUNTDOWN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CAPTURE_TYPE_COUNTDOWN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		capture_countdown_unref (old);
	}
}


static void capture_countdown_class_init (CaptureCountdownClass * klass) {
	capture_countdown_parent_class = g_type_class_peek_parent (klass);
	((CaptureCountdownClass *) klass)->finalize = capture_countdown_finalize;
	g_type_class_add_private (klass, sizeof (CaptureCountdownPrivate));
	g_signal_new ("tick", CAPTURE_TYPE_COUNTDOWN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_DOUBLE, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_DOUBLE);
	g_signal_new ("ignition", CAPTURE_TYPE_COUNTDOWN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void capture_countdown_instance_init (CaptureCountdown * self) {
	self->priv = CAPTURE_COUNTDOWN_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void capture_countdown_finalize (CaptureCountdown* obj) {
	CaptureCountdown * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CAPTURE_TYPE_COUNTDOWN, CaptureCountdown);
	g_signal_handlers_destroy (self);
}


GType capture_countdown_get_type (void) {
	static volatile gsize capture_countdown_type_id__volatile = 0;
	if (g_once_init_enter (&capture_countdown_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { capture_value_countdown_init, capture_value_countdown_free_value, capture_value_countdown_copy_value, capture_value_countdown_peek_pointer, "p", capture_value_countdown_collect_value, "p", capture_value_countdown_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CaptureCountdownClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) capture_countdown_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaptureCountdown), 0, (GInstanceInitFunc) capture_countdown_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType capture_countdown_type_id;
		capture_countdown_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CaptureCountdown", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&capture_countdown_type_id__volatile, capture_countdown_type_id);
	}
	return capture_countdown_type_id__volatile;
}


gpointer capture_countdown_ref (gpointer instance) {
	CaptureCountdown* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void capture_countdown_unref (gpointer instance) {
	CaptureCountdown* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CAPTURE_COUNTDOWN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



