/* RegionSelect.c generated by valac 0.34.4, the Vala compiler
 * generated from RegionSelect.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <string.h>
#include <stdio.h>
#include <cairo.h>
#include <stdlib.h>
#include <plank.h>
#include <float.h>
#include <math.h>


#define CAPTURE_TYPE_DRAG_STATUS (capture_drag_status_get_type ())

#define CAPTURE_TYPE_SELECTION_MODE (capture_selection_mode_get_type ())

#define CAPTURE_TYPE_REGION_SELECT (capture_region_select_get_type ())
#define CAPTURE_REGION_SELECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAPTURE_TYPE_REGION_SELECT, CaptureRegionSelect))
#define CAPTURE_REGION_SELECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAPTURE_TYPE_REGION_SELECT, CaptureRegionSelectClass))
#define CAPTURE_IS_REGION_SELECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAPTURE_TYPE_REGION_SELECT))
#define CAPTURE_IS_REGION_SELECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAPTURE_TYPE_REGION_SELECT))
#define CAPTURE_REGION_SELECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAPTURE_TYPE_REGION_SELECT, CaptureRegionSelectClass))

typedef struct _CaptureRegionSelect CaptureRegionSelect;
typedef struct _CaptureRegionSelectClass CaptureRegionSelectClass;
typedef struct _CaptureRegionSelectPrivate CaptureRegionSelectPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))

typedef enum  {
	CAPTURE_DRAG_STATUS_NONE,
	CAPTURE_DRAG_STATUS_NORTHWEST,
	CAPTURE_DRAG_STATUS_NORTHEAST,
	CAPTURE_DRAG_STATUS_SOUTHEAST,
	CAPTURE_DRAG_STATUS_SOUTHWEST,
	CAPTURE_DRAG_STATUS_NORTH,
	CAPTURE_DRAG_STATUS_EAST,
	CAPTURE_DRAG_STATUS_SOUTH,
	CAPTURE_DRAG_STATUS_WEST,
	CAPTURE_DRAG_STATUS_MOVE
} CaptureDragStatus;

typedef enum  {
	CAPTURE_SELECTION_MODE_SELECTION,
	CAPTURE_SELECTION_MODE_FULL_SCREEN,
	CAPTURE_SELECTION_MODE_FULL_DISPLAY
} CaptureSelectionMode;

struct _CaptureRegionSelect {
	GraniteWidgetsCompositedWindow parent_instance;
	CaptureRegionSelectPrivate * priv;
	GtkDrawingArea* drawing_area;
	GdkDevice* mouse;
	GdkWindow* gwin;
	GdkRectangle selection;
};

struct _CaptureRegionSelectClass {
	GraniteWidgetsCompositedWindowClass parent_class;
};

struct _CaptureRegionSelectPrivate {
	CaptureDragStatus status;
	CaptureSelectionMode mode;
	gint delta_x;
	gint delta_y;
	GdkRectangle _selection;
	gboolean aborted;
	GSettings* settings;
};

struct _Block2Data {
	int _ref_count_;
	CaptureRegionSelect* self;
	GdkCursor** cursors;
	gint cursors_length1;
	gint _cursors_size_;
};


static gpointer capture_region_select_parent_class = NULL;

GType capture_drag_status_get_type (void) G_GNUC_CONST;
GType capture_selection_mode_get_type (void) G_GNUC_CONST;
GType capture_region_select_get_type (void) G_GNUC_CONST;
#define CAPTURE_REGION_SELECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CAPTURE_TYPE_REGION_SELECT, CaptureRegionSelectPrivate))
enum  {
	CAPTURE_REGION_SELECT_DUMMY_PROPERTY
};
CaptureRegionSelect* capture_region_select_new (void);
CaptureRegionSelect* capture_region_select_construct (GType object_type);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
gboolean capture_region_select_on_draw (CaptureRegionSelect* self, cairo_t* ctx);
static gboolean _capture_region_select_on_draw_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static gboolean __lambda19_ (CaptureRegionSelect* self, GdkEventButton* context);
static gboolean capture_region_select_is_near (CaptureRegionSelect* self, gint x1, gint y1, gint x2, gint y2, gint radius);
static gboolean ___lambda19__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda20_ (Block2Data* _data2_, GdkEventMotion* event);
static gboolean ___lambda20__gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self);
static gboolean __lambda21_ (CaptureRegionSelect* self, GdkEventButton* context);
static gboolean ___lambda21__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda22_ (CaptureRegionSelect* self, GdkEventKey* event_key);
static void capture_region_select_toggle_mode (CaptureRegionSelect* self);
static gboolean ___lambda22__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
GtkResponseType capture_region_select_run (CaptureRegionSelect* self);
void capture_region_select_get_selection (CaptureRegionSelect* self, GdkRectangle* result);
static void capture_region_select_debug_selection (CaptureRegionSelect* self);
static void capture_region_select_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


GType capture_drag_status_get_type (void) {
	static volatile gsize capture_drag_status_type_id__volatile = 0;
	if (g_once_init_enter (&capture_drag_status_type_id__volatile)) {
		static const GEnumValue values[] = {{CAPTURE_DRAG_STATUS_NONE, "CAPTURE_DRAG_STATUS_NONE", "none"}, {CAPTURE_DRAG_STATUS_NORTHWEST, "CAPTURE_DRAG_STATUS_NORTHWEST", "northwest"}, {CAPTURE_DRAG_STATUS_NORTHEAST, "CAPTURE_DRAG_STATUS_NORTHEAST", "northeast"}, {CAPTURE_DRAG_STATUS_SOUTHEAST, "CAPTURE_DRAG_STATUS_SOUTHEAST", "southeast"}, {CAPTURE_DRAG_STATUS_SOUTHWEST, "CAPTURE_DRAG_STATUS_SOUTHWEST", "southwest"}, {CAPTURE_DRAG_STATUS_NORTH, "CAPTURE_DRAG_STATUS_NORTH", "north"}, {CAPTURE_DRAG_STATUS_EAST, "CAPTURE_DRAG_STATUS_EAST", "east"}, {CAPTURE_DRAG_STATUS_SOUTH, "CAPTURE_DRAG_STATUS_SOUTH", "south"}, {CAPTURE_DRAG_STATUS_WEST, "CAPTURE_DRAG_STATUS_WEST", "west"}, {CAPTURE_DRAG_STATUS_MOVE, "CAPTURE_DRAG_STATUS_MOVE", "move"}, {0, NULL, NULL}};
		GType capture_drag_status_type_id;
		capture_drag_status_type_id = g_enum_register_static ("CaptureDragStatus", values);
		g_once_init_leave (&capture_drag_status_type_id__volatile, capture_drag_status_type_id);
	}
	return capture_drag_status_type_id__volatile;
}


GType capture_selection_mode_get_type (void) {
	static volatile gsize capture_selection_mode_type_id__volatile = 0;
	if (g_once_init_enter (&capture_selection_mode_type_id__volatile)) {
		static const GEnumValue values[] = {{CAPTURE_SELECTION_MODE_SELECTION, "CAPTURE_SELECTION_MODE_SELECTION", "selection"}, {CAPTURE_SELECTION_MODE_FULL_SCREEN, "CAPTURE_SELECTION_MODE_FULL_SCREEN", "full-screen"}, {CAPTURE_SELECTION_MODE_FULL_DISPLAY, "CAPTURE_SELECTION_MODE_FULL_DISPLAY", "full-display"}, {0, NULL, NULL}};
		GType capture_selection_mode_type_id;
		capture_selection_mode_type_id = g_enum_register_static ("CaptureSelectionMode", values);
		g_once_init_leave (&capture_selection_mode_type_id__volatile, capture_selection_mode_type_id);
	}
	return capture_selection_mode_type_id__volatile;
}


/**
  * Constructor
  */
static Block2Data* block2_data_ref (Block2Data* _data2_) {
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		CaptureRegionSelect* self;
		self = _data2_->self;
		_data2_->cursors = (_vala_array_free (_data2_->cursors, _data2_->cursors_length1, (GDestroyNotify) g_object_unref), NULL);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}


static gboolean _capture_region_select_on_draw_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = capture_region_select_on_draw ((CaptureRegionSelect*) self, cr);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean __lambda19_ (CaptureRegionSelect* self, GdkEventButton* context) {
	gboolean result = FALSE;
	gint x = 0;
	gint y = 0;
	GdkWindow* _tmp0_ = NULL;
	GdkDevice* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	GdkRectangle _tmp6_ = {0};
	gint _tmp7_ = 0;
	GdkRectangle _tmp8_ = {0};
	gint _tmp9_ = 0;
	gboolean _tmp10_ = FALSE;
	gint _tmp101_ = 0;
	gint _tmp102_ = 0;
	g_return_val_if_fail (context != NULL, FALSE);
	_tmp0_ = gdk_get_default_root_window ();
	_tmp1_ = self->mouse;
	gdk_window_get_device_position (_tmp0_, _tmp1_, &_tmp2_, &_tmp3_, NULL);
	x = _tmp2_;
	y = _tmp3_;
	_tmp4_ = x;
	_tmp5_ = y;
	_tmp6_ = self->selection;
	_tmp7_ = _tmp6_.x;
	_tmp8_ = self->selection;
	_tmp9_ = _tmp8_.y;
	_tmp10_ = capture_region_select_is_near (self, _tmp4_, _tmp5_, _tmp7_, _tmp9_, 30);
	if (_tmp10_) {
		self->priv->status = CAPTURE_DRAG_STATUS_NORTHWEST;
		result = TRUE;
		return result;
	} else {
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		GdkRectangle _tmp13_ = {0};
		gint _tmp14_ = 0;
		GdkRectangle _tmp15_ = {0};
		gint _tmp16_ = 0;
		GdkRectangle _tmp17_ = {0};
		gint _tmp18_ = 0;
		gboolean _tmp19_ = FALSE;
		_tmp11_ = x;
		_tmp12_ = y;
		_tmp13_ = self->selection;
		_tmp14_ = _tmp13_.x;
		_tmp15_ = self->selection;
		_tmp16_ = _tmp15_.width;
		_tmp17_ = self->selection;
		_tmp18_ = _tmp17_.y;
		_tmp19_ = capture_region_select_is_near (self, _tmp11_, _tmp12_, _tmp14_ + _tmp16_, _tmp18_, 30);
		if (_tmp19_) {
			self->priv->status = CAPTURE_DRAG_STATUS_NORTHEAST;
			result = TRUE;
			return result;
		} else {
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			GdkRectangle _tmp22_ = {0};
			gint _tmp23_ = 0;
			GdkRectangle _tmp24_ = {0};
			gint _tmp25_ = 0;
			GdkRectangle _tmp26_ = {0};
			gint _tmp27_ = 0;
			GdkRectangle _tmp28_ = {0};
			gint _tmp29_ = 0;
			gboolean _tmp30_ = FALSE;
			_tmp20_ = x;
			_tmp21_ = y;
			_tmp22_ = self->selection;
			_tmp23_ = _tmp22_.x;
			_tmp24_ = self->selection;
			_tmp25_ = _tmp24_.width;
			_tmp26_ = self->selection;
			_tmp27_ = _tmp26_.y;
			_tmp28_ = self->selection;
			_tmp29_ = _tmp28_.height;
			_tmp30_ = capture_region_select_is_near (self, _tmp20_, _tmp21_, _tmp23_ + _tmp25_, _tmp27_ + _tmp29_, 30);
			if (_tmp30_) {
				self->priv->status = CAPTURE_DRAG_STATUS_SOUTHEAST;
				result = TRUE;
				return result;
			} else {
				gint _tmp31_ = 0;
				gint _tmp32_ = 0;
				GdkRectangle _tmp33_ = {0};
				gint _tmp34_ = 0;
				GdkRectangle _tmp35_ = {0};
				gint _tmp36_ = 0;
				GdkRectangle _tmp37_ = {0};
				gint _tmp38_ = 0;
				gboolean _tmp39_ = FALSE;
				_tmp31_ = x;
				_tmp32_ = y;
				_tmp33_ = self->selection;
				_tmp34_ = _tmp33_.x;
				_tmp35_ = self->selection;
				_tmp36_ = _tmp35_.y;
				_tmp37_ = self->selection;
				_tmp38_ = _tmp37_.height;
				_tmp39_ = capture_region_select_is_near (self, _tmp31_, _tmp32_, _tmp34_, _tmp36_ + _tmp38_, 30);
				if (_tmp39_) {
					self->priv->status = CAPTURE_DRAG_STATUS_SOUTHWEST;
					result = TRUE;
					return result;
				} else {
					gboolean _tmp40_ = FALSE;
					gboolean _tmp41_ = FALSE;
					gboolean _tmp42_ = FALSE;
					gint _tmp43_ = 0;
					GdkRectangle _tmp44_ = {0};
					gint _tmp45_ = 0;
					_tmp43_ = x;
					_tmp44_ = self->selection;
					_tmp45_ = _tmp44_.x;
					if (_tmp43_ >= _tmp45_) {
						gint _tmp46_ = 0;
						GdkRectangle _tmp47_ = {0};
						gint _tmp48_ = 0;
						GdkRectangle _tmp49_ = {0};
						gint _tmp50_ = 0;
						_tmp46_ = x;
						_tmp47_ = self->selection;
						_tmp48_ = _tmp47_.x;
						_tmp49_ = self->selection;
						_tmp50_ = _tmp49_.width;
						_tmp42_ = _tmp46_ < (_tmp48_ + _tmp50_);
					} else {
						_tmp42_ = FALSE;
					}
					if (_tmp42_) {
						gint _tmp51_ = 0;
						GdkRectangle _tmp52_ = {0};
						gint _tmp53_ = 0;
						_tmp51_ = y;
						_tmp52_ = self->selection;
						_tmp53_ = _tmp52_.y;
						_tmp41_ = _tmp51_ > _tmp53_;
					} else {
						_tmp41_ = FALSE;
					}
					if (_tmp41_) {
						gint _tmp54_ = 0;
						GdkRectangle _tmp55_ = {0};
						gint _tmp56_ = 0;
						GdkRectangle _tmp57_ = {0};
						gint _tmp58_ = 0;
						_tmp54_ = y;
						_tmp55_ = self->selection;
						_tmp56_ = _tmp55_.y;
						_tmp57_ = self->selection;
						_tmp58_ = _tmp57_.height;
						_tmp40_ = _tmp54_ < (_tmp56_ + _tmp58_);
					} else {
						_tmp40_ = FALSE;
					}
					if (_tmp40_) {
						gint _tmp59_ = 0;
						GdkRectangle _tmp60_ = {0};
						gint _tmp61_ = 0;
						gint _tmp62_ = 0;
						GdkRectangle _tmp63_ = {0};
						gint _tmp64_ = 0;
						self->priv->status = CAPTURE_DRAG_STATUS_MOVE;
						_tmp59_ = x;
						_tmp60_ = self->selection;
						_tmp61_ = _tmp60_.x;
						self->priv->delta_x = _tmp59_ - _tmp61_;
						_tmp62_ = y;
						_tmp63_ = self->selection;
						_tmp64_ = _tmp63_.y;
						self->priv->delta_y = _tmp62_ - _tmp64_;
						result = TRUE;
						return result;
					} else {
						gboolean _tmp65_ = FALSE;
						gint _tmp66_ = 0;
						GdkRectangle _tmp67_ = {0};
						gint _tmp68_ = 0;
						_tmp66_ = x;
						_tmp67_ = self->selection;
						_tmp68_ = _tmp67_.x;
						if (_tmp66_ >= (_tmp68_ - 15)) {
							gint _tmp69_ = 0;
							GdkRectangle _tmp70_ = {0};
							gint _tmp71_ = 0;
							_tmp69_ = x;
							_tmp70_ = self->selection;
							_tmp71_ = _tmp70_.x;
							_tmp65_ = _tmp69_ <= (_tmp71_ + 15);
						} else {
							_tmp65_ = FALSE;
						}
						if (_tmp65_) {
							self->priv->status = CAPTURE_DRAG_STATUS_WEST;
							result = TRUE;
							return result;
						} else {
							gboolean _tmp72_ = FALSE;
							gint _tmp73_ = 0;
							GdkRectangle _tmp74_ = {0};
							gint _tmp75_ = 0;
							GdkRectangle _tmp76_ = {0};
							gint _tmp77_ = 0;
							_tmp73_ = x;
							_tmp74_ = self->selection;
							_tmp75_ = _tmp74_.x;
							_tmp76_ = self->selection;
							_tmp77_ = _tmp76_.width;
							if (_tmp73_ >= ((_tmp75_ + _tmp77_) - 15)) {
								gint _tmp78_ = 0;
								GdkRectangle _tmp79_ = {0};
								gint _tmp80_ = 0;
								GdkRectangle _tmp81_ = {0};
								gint _tmp82_ = 0;
								_tmp78_ = x;
								_tmp79_ = self->selection;
								_tmp80_ = _tmp79_.x;
								_tmp81_ = self->selection;
								_tmp82_ = _tmp81_.width;
								_tmp72_ = _tmp78_ <= ((_tmp80_ + _tmp82_) + 15);
							} else {
								_tmp72_ = FALSE;
							}
							if (_tmp72_) {
								self->priv->status = CAPTURE_DRAG_STATUS_EAST;
								result = TRUE;
								return result;
							} else {
								gboolean _tmp83_ = FALSE;
								gint _tmp84_ = 0;
								GdkRectangle _tmp85_ = {0};
								gint _tmp86_ = 0;
								GdkRectangle _tmp87_ = {0};
								gint _tmp88_ = 0;
								_tmp84_ = y;
								_tmp85_ = self->selection;
								_tmp86_ = _tmp85_.y;
								_tmp87_ = self->selection;
								_tmp88_ = _tmp87_.height;
								if (_tmp84_ >= ((_tmp86_ + _tmp88_) - 15)) {
									gint _tmp89_ = 0;
									GdkRectangle _tmp90_ = {0};
									gint _tmp91_ = 0;
									GdkRectangle _tmp92_ = {0};
									gint _tmp93_ = 0;
									_tmp89_ = y;
									_tmp90_ = self->selection;
									_tmp91_ = _tmp90_.y;
									_tmp92_ = self->selection;
									_tmp93_ = _tmp92_.height;
									_tmp83_ = _tmp89_ <= ((_tmp91_ + _tmp93_) + 15);
								} else {
									_tmp83_ = FALSE;
								}
								if (_tmp83_) {
									self->priv->status = CAPTURE_DRAG_STATUS_SOUTH;
									result = TRUE;
									return result;
								} else {
									gboolean _tmp94_ = FALSE;
									gint _tmp95_ = 0;
									GdkRectangle _tmp96_ = {0};
									gint _tmp97_ = 0;
									_tmp95_ = y;
									_tmp96_ = self->selection;
									_tmp97_ = _tmp96_.y;
									if (_tmp95_ >= (_tmp97_ - 15)) {
										gint _tmp98_ = 0;
										GdkRectangle _tmp99_ = {0};
										gint _tmp100_ = 0;
										_tmp98_ = y;
										_tmp99_ = self->selection;
										_tmp100_ = _tmp99_.y;
										_tmp94_ = _tmp98_ <= (_tmp100_ + 15);
									} else {
										_tmp94_ = FALSE;
									}
									if (_tmp94_) {
										self->priv->status = CAPTURE_DRAG_STATUS_NORTH;
										result = TRUE;
										return result;
									}
								}
							}
						}
					}
				}
			}
		}
	}
	_tmp101_ = x;
	self->selection.x = _tmp101_;
	_tmp102_ = y;
	self->selection.y = _tmp102_;
	self->priv->status = CAPTURE_DRAG_STATUS_SOUTHEAST;
	result = TRUE;
	return result;
}


static gboolean ___lambda19__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda19_ ((CaptureRegionSelect*) self, event);
	return result;
}


static gboolean __lambda20_ (Block2Data* _data2_, GdkEventMotion* event) {
	CaptureRegionSelect* self;
	gboolean result = FALSE;
	gint x = 0;
	gint y = 0;
	GdkWindow* _tmp0_ = NULL;
	GdkDevice* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	GdkRectangle _tmp6_ = {0};
	gint _tmp7_ = 0;
	GdkRectangle _tmp8_ = {0};
	gint _tmp9_ = 0;
	gboolean _tmp10_ = FALSE;
	CaptureDragStatus _tmp115_ = 0;
	CaptureDragStatus _tmp178_ = 0;
	self = _data2_->self;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->gwin;
	_tmp1_ = self->mouse;
	gdk_window_get_device_position (_tmp0_, _tmp1_, &_tmp2_, &_tmp3_, NULL);
	x = _tmp2_;
	y = _tmp3_;
	_tmp4_ = x;
	_tmp5_ = y;
	_tmp6_ = self->selection;
	_tmp7_ = _tmp6_.x;
	_tmp8_ = self->selection;
	_tmp9_ = _tmp8_.y;
	_tmp10_ = capture_region_select_is_near (self, _tmp4_, _tmp5_, _tmp7_, _tmp9_, 30);
	if (_tmp10_) {
		GdkWindow* _tmp11_ = NULL;
		GdkCursor* _tmp12_ = NULL;
		_tmp11_ = self->gwin;
		_tmp12_ = _data2_->cursors[CAPTURE_DRAG_STATUS_NORTHWEST];
		gdk_window_set_cursor (_tmp11_, _tmp12_);
	} else {
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		GdkRectangle _tmp15_ = {0};
		gint _tmp16_ = 0;
		GdkRectangle _tmp17_ = {0};
		gint _tmp18_ = 0;
		GdkRectangle _tmp19_ = {0};
		gint _tmp20_ = 0;
		gboolean _tmp21_ = FALSE;
		_tmp13_ = x;
		_tmp14_ = y;
		_tmp15_ = self->selection;
		_tmp16_ = _tmp15_.x;
		_tmp17_ = self->selection;
		_tmp18_ = _tmp17_.width;
		_tmp19_ = self->selection;
		_tmp20_ = _tmp19_.y;
		_tmp21_ = capture_region_select_is_near (self, _tmp13_, _tmp14_, _tmp16_ + _tmp18_, _tmp20_, 30);
		if (_tmp21_) {
			GdkWindow* _tmp22_ = NULL;
			GdkCursor* _tmp23_ = NULL;
			_tmp22_ = self->gwin;
			_tmp23_ = _data2_->cursors[CAPTURE_DRAG_STATUS_NORTHEAST];
			gdk_window_set_cursor (_tmp22_, _tmp23_);
		} else {
			gint _tmp24_ = 0;
			gint _tmp25_ = 0;
			GdkRectangle _tmp26_ = {0};
			gint _tmp27_ = 0;
			GdkRectangle _tmp28_ = {0};
			gint _tmp29_ = 0;
			GdkRectangle _tmp30_ = {0};
			gint _tmp31_ = 0;
			GdkRectangle _tmp32_ = {0};
			gint _tmp33_ = 0;
			gboolean _tmp34_ = FALSE;
			_tmp24_ = x;
			_tmp25_ = y;
			_tmp26_ = self->selection;
			_tmp27_ = _tmp26_.x;
			_tmp28_ = self->selection;
			_tmp29_ = _tmp28_.width;
			_tmp30_ = self->selection;
			_tmp31_ = _tmp30_.y;
			_tmp32_ = self->selection;
			_tmp33_ = _tmp32_.height;
			_tmp34_ = capture_region_select_is_near (self, _tmp24_, _tmp25_, _tmp27_ + _tmp29_, _tmp31_ + _tmp33_, 30);
			if (_tmp34_) {
				GdkWindow* _tmp35_ = NULL;
				GdkCursor* _tmp36_ = NULL;
				_tmp35_ = self->gwin;
				_tmp36_ = _data2_->cursors[CAPTURE_DRAG_STATUS_SOUTHEAST];
				gdk_window_set_cursor (_tmp35_, _tmp36_);
			} else {
				gint _tmp37_ = 0;
				gint _tmp38_ = 0;
				GdkRectangle _tmp39_ = {0};
				gint _tmp40_ = 0;
				GdkRectangle _tmp41_ = {0};
				gint _tmp42_ = 0;
				GdkRectangle _tmp43_ = {0};
				gint _tmp44_ = 0;
				gboolean _tmp45_ = FALSE;
				_tmp37_ = x;
				_tmp38_ = y;
				_tmp39_ = self->selection;
				_tmp40_ = _tmp39_.x;
				_tmp41_ = self->selection;
				_tmp42_ = _tmp41_.y;
				_tmp43_ = self->selection;
				_tmp44_ = _tmp43_.height;
				_tmp45_ = capture_region_select_is_near (self, _tmp37_, _tmp38_, _tmp40_, _tmp42_ + _tmp44_, 30);
				if (_tmp45_) {
					GdkWindow* _tmp46_ = NULL;
					GdkCursor* _tmp47_ = NULL;
					_tmp46_ = self->gwin;
					_tmp47_ = _data2_->cursors[CAPTURE_DRAG_STATUS_SOUTHWEST];
					gdk_window_set_cursor (_tmp46_, _tmp47_);
				} else {
					gboolean _tmp48_ = FALSE;
					gboolean _tmp49_ = FALSE;
					gboolean _tmp50_ = FALSE;
					gint _tmp51_ = 0;
					GdkRectangle _tmp52_ = {0};
					gint _tmp53_ = 0;
					_tmp51_ = x;
					_tmp52_ = self->selection;
					_tmp53_ = _tmp52_.x;
					if (_tmp51_ >= _tmp53_) {
						gint _tmp54_ = 0;
						GdkRectangle _tmp55_ = {0};
						gint _tmp56_ = 0;
						GdkRectangle _tmp57_ = {0};
						gint _tmp58_ = 0;
						_tmp54_ = x;
						_tmp55_ = self->selection;
						_tmp56_ = _tmp55_.x;
						_tmp57_ = self->selection;
						_tmp58_ = _tmp57_.width;
						_tmp50_ = _tmp54_ < (_tmp56_ + _tmp58_);
					} else {
						_tmp50_ = FALSE;
					}
					if (_tmp50_) {
						gint _tmp59_ = 0;
						GdkRectangle _tmp60_ = {0};
						gint _tmp61_ = 0;
						_tmp59_ = y;
						_tmp60_ = self->selection;
						_tmp61_ = _tmp60_.y;
						_tmp49_ = _tmp59_ > _tmp61_;
					} else {
						_tmp49_ = FALSE;
					}
					if (_tmp49_) {
						gint _tmp62_ = 0;
						GdkRectangle _tmp63_ = {0};
						gint _tmp64_ = 0;
						GdkRectangle _tmp65_ = {0};
						gint _tmp66_ = 0;
						_tmp62_ = y;
						_tmp63_ = self->selection;
						_tmp64_ = _tmp63_.y;
						_tmp65_ = self->selection;
						_tmp66_ = _tmp65_.height;
						_tmp48_ = _tmp62_ < (_tmp64_ + _tmp66_);
					} else {
						_tmp48_ = FALSE;
					}
					if (_tmp48_) {
						GdkWindow* _tmp67_ = NULL;
						GdkCursor* _tmp68_ = NULL;
						_tmp67_ = self->gwin;
						_tmp68_ = _data2_->cursors[CAPTURE_DRAG_STATUS_MOVE];
						gdk_window_set_cursor (_tmp67_, _tmp68_);
					} else {
						gboolean _tmp69_ = FALSE;
						gint _tmp70_ = 0;
						GdkRectangle _tmp71_ = {0};
						gint _tmp72_ = 0;
						_tmp70_ = x;
						_tmp71_ = self->selection;
						_tmp72_ = _tmp71_.x;
						if (_tmp70_ >= (_tmp72_ - 15)) {
							gint _tmp73_ = 0;
							GdkRectangle _tmp74_ = {0};
							gint _tmp75_ = 0;
							_tmp73_ = x;
							_tmp74_ = self->selection;
							_tmp75_ = _tmp74_.x;
							_tmp69_ = _tmp73_ <= (_tmp75_ + 15);
						} else {
							_tmp69_ = FALSE;
						}
						if (_tmp69_) {
							GdkWindow* _tmp76_ = NULL;
							GdkCursor* _tmp77_ = NULL;
							_tmp76_ = self->gwin;
							_tmp77_ = _data2_->cursors[CAPTURE_DRAG_STATUS_WEST];
							gdk_window_set_cursor (_tmp76_, _tmp77_);
						} else {
							gboolean _tmp78_ = FALSE;
							gint _tmp79_ = 0;
							GdkRectangle _tmp80_ = {0};
							gint _tmp81_ = 0;
							GdkRectangle _tmp82_ = {0};
							gint _tmp83_ = 0;
							_tmp79_ = x;
							_tmp80_ = self->selection;
							_tmp81_ = _tmp80_.x;
							_tmp82_ = self->selection;
							_tmp83_ = _tmp82_.width;
							if (_tmp79_ >= ((_tmp81_ + _tmp83_) - 15)) {
								gint _tmp84_ = 0;
								GdkRectangle _tmp85_ = {0};
								gint _tmp86_ = 0;
								GdkRectangle _tmp87_ = {0};
								gint _tmp88_ = 0;
								_tmp84_ = x;
								_tmp85_ = self->selection;
								_tmp86_ = _tmp85_.x;
								_tmp87_ = self->selection;
								_tmp88_ = _tmp87_.width;
								_tmp78_ = _tmp84_ <= ((_tmp86_ + _tmp88_) + 15);
							} else {
								_tmp78_ = FALSE;
							}
							if (_tmp78_) {
								GdkWindow* _tmp89_ = NULL;
								GdkCursor* _tmp90_ = NULL;
								_tmp89_ = self->gwin;
								_tmp90_ = _data2_->cursors[CAPTURE_DRAG_STATUS_EAST];
								gdk_window_set_cursor (_tmp89_, _tmp90_);
							} else {
								gboolean _tmp91_ = FALSE;
								gint _tmp92_ = 0;
								GdkRectangle _tmp93_ = {0};
								gint _tmp94_ = 0;
								GdkRectangle _tmp95_ = {0};
								gint _tmp96_ = 0;
								_tmp92_ = y;
								_tmp93_ = self->selection;
								_tmp94_ = _tmp93_.y;
								_tmp95_ = self->selection;
								_tmp96_ = _tmp95_.height;
								if (_tmp92_ >= ((_tmp94_ + _tmp96_) - 15)) {
									gint _tmp97_ = 0;
									GdkRectangle _tmp98_ = {0};
									gint _tmp99_ = 0;
									GdkRectangle _tmp100_ = {0};
									gint _tmp101_ = 0;
									_tmp97_ = y;
									_tmp98_ = self->selection;
									_tmp99_ = _tmp98_.y;
									_tmp100_ = self->selection;
									_tmp101_ = _tmp100_.height;
									_tmp91_ = _tmp97_ <= ((_tmp99_ + _tmp101_) + 15);
								} else {
									_tmp91_ = FALSE;
								}
								if (_tmp91_) {
									GdkWindow* _tmp102_ = NULL;
									GdkCursor* _tmp103_ = NULL;
									_tmp102_ = self->gwin;
									_tmp103_ = _data2_->cursors[CAPTURE_DRAG_STATUS_SOUTH];
									gdk_window_set_cursor (_tmp102_, _tmp103_);
								} else {
									gboolean _tmp104_ = FALSE;
									gint _tmp105_ = 0;
									GdkRectangle _tmp106_ = {0};
									gint _tmp107_ = 0;
									_tmp105_ = y;
									_tmp106_ = self->selection;
									_tmp107_ = _tmp106_.y;
									if (_tmp105_ >= (_tmp107_ - 15)) {
										gint _tmp108_ = 0;
										GdkRectangle _tmp109_ = {0};
										gint _tmp110_ = 0;
										_tmp108_ = y;
										_tmp109_ = self->selection;
										_tmp110_ = _tmp109_.y;
										_tmp104_ = _tmp108_ <= (_tmp110_ + 15);
									} else {
										_tmp104_ = FALSE;
									}
									if (_tmp104_) {
										GdkWindow* _tmp111_ = NULL;
										GdkCursor* _tmp112_ = NULL;
										_tmp111_ = self->gwin;
										_tmp112_ = _data2_->cursors[CAPTURE_DRAG_STATUS_NORTH];
										gdk_window_set_cursor (_tmp111_, _tmp112_);
									} else {
										GdkWindow* _tmp113_ = NULL;
										GdkCursor* _tmp114_ = NULL;
										_tmp113_ = self->gwin;
										_tmp114_ = _data2_->cursors[CAPTURE_DRAG_STATUS_NONE];
										gdk_window_set_cursor (_tmp113_, _tmp114_);
									}
								}
							}
						}
					}
				}
			}
		}
	}
	_tmp115_ = self->priv->status;
	switch (_tmp115_) {
		case CAPTURE_DRAG_STATUS_NORTHWEST:
		{
			gint _tmp116_ = 0;
			GdkRectangle _tmp117_ = {0};
			gint _tmp118_ = 0;
			gint _tmp119_ = 0;
			gint _tmp120_ = 0;
			GdkRectangle _tmp121_ = {0};
			gint _tmp122_ = 0;
			gint _tmp123_ = 0;
			gint _tmp124_ = 0;
			gint _tmp125_ = 0;
			_tmp116_ = self->selection.width;
			_tmp117_ = self->selection;
			_tmp118_ = _tmp117_.x;
			_tmp119_ = x;
			self->selection.width = _tmp116_ + (_tmp118_ - _tmp119_);
			_tmp120_ = self->selection.height;
			_tmp121_ = self->selection;
			_tmp122_ = _tmp121_.y;
			_tmp123_ = y;
			self->selection.height = _tmp120_ + (_tmp122_ - _tmp123_);
			_tmp124_ = x;
			self->selection.x = _tmp124_;
			_tmp125_ = y;
			self->selection.y = _tmp125_;
			break;
		}
		case CAPTURE_DRAG_STATUS_NORTHEAST:
		{
			gint _tmp126_ = 0;
			GdkRectangle _tmp127_ = {0};
			gint _tmp128_ = 0;
			gint _tmp129_ = 0;
			GdkRectangle _tmp130_ = {0};
			gint _tmp131_ = 0;
			gint _tmp132_ = 0;
			gint _tmp133_ = 0;
			_tmp126_ = x;
			_tmp127_ = self->selection;
			_tmp128_ = _tmp127_.x;
			self->selection.width = _tmp126_ - _tmp128_;
			_tmp129_ = self->selection.height;
			_tmp130_ = self->selection;
			_tmp131_ = _tmp130_.y;
			_tmp132_ = y;
			self->selection.height = _tmp129_ + (_tmp131_ - _tmp132_);
			_tmp133_ = y;
			self->selection.y = _tmp133_;
			break;
		}
		case CAPTURE_DRAG_STATUS_SOUTHEAST:
		{
			gint _tmp134_ = 0;
			GdkRectangle _tmp135_ = {0};
			gint _tmp136_ = 0;
			gint _tmp137_ = 0;
			GdkRectangle _tmp138_ = {0};
			gint _tmp139_ = 0;
			_tmp134_ = x;
			_tmp135_ = self->selection;
			_tmp136_ = _tmp135_.x;
			self->selection.width = _tmp134_ - _tmp136_;
			_tmp137_ = y;
			_tmp138_ = self->selection;
			_tmp139_ = _tmp138_.y;
			self->selection.height = _tmp137_ - _tmp139_;
			break;
		}
		case CAPTURE_DRAG_STATUS_SOUTHWEST:
		{
			gint _tmp140_ = 0;
			GdkRectangle _tmp141_ = {0};
			gint _tmp142_ = 0;
			gint _tmp143_ = 0;
			gint _tmp144_ = 0;
			GdkRectangle _tmp145_ = {0};
			gint _tmp146_ = 0;
			gint _tmp147_ = 0;
			_tmp140_ = self->selection.width;
			_tmp141_ = self->selection;
			_tmp142_ = _tmp141_.x;
			_tmp143_ = x;
			self->selection.width = _tmp140_ + (_tmp142_ - _tmp143_);
			_tmp144_ = y;
			_tmp145_ = self->selection;
			_tmp146_ = _tmp145_.y;
			self->selection.height = _tmp144_ - _tmp146_;
			_tmp147_ = x;
			self->selection.x = _tmp147_;
			break;
		}
		case CAPTURE_DRAG_STATUS_MOVE:
		{
			gint _tmp148_ = 0;
			gint _tmp149_ = 0;
			GdkWindow* _tmp150_ = NULL;
			gint _tmp151_ = 0;
			GdkRectangle _tmp152_ = {0};
			gint _tmp153_ = 0;
			gint _tmp154_ = 0;
			gint _tmp155_ = 0;
			gint _tmp156_ = 0;
			GdkWindow* _tmp157_ = NULL;
			gint _tmp158_ = 0;
			GdkRectangle _tmp159_ = {0};
			gint _tmp160_ = 0;
			gint _tmp161_ = 0;
			_tmp148_ = x;
			_tmp149_ = self->priv->delta_x;
			_tmp150_ = self->gwin;
			_tmp151_ = gdk_window_get_width (_tmp150_);
			_tmp152_ = self->selection;
			_tmp153_ = _tmp152_.width;
			_tmp154_ = CLAMP (_tmp148_ - _tmp149_, 0, _tmp151_ - _tmp153_);
			self->selection.x = _tmp154_;
			_tmp155_ = y;
			_tmp156_ = self->priv->delta_y;
			_tmp157_ = self->gwin;
			_tmp158_ = gdk_window_get_height (_tmp157_);
			_tmp159_ = self->selection;
			_tmp160_ = _tmp159_.height;
			_tmp161_ = CLAMP (_tmp155_ - _tmp156_, 0, _tmp158_ - _tmp160_);
			self->selection.y = _tmp161_;
			break;
		}
		case CAPTURE_DRAG_STATUS_NORTH:
		{
			gint _tmp162_ = 0;
			GdkRectangle _tmp163_ = {0};
			gint _tmp164_ = 0;
			gint _tmp165_ = 0;
			gint _tmp166_ = 0;
			_tmp162_ = self->selection.height;
			_tmp163_ = self->selection;
			_tmp164_ = _tmp163_.y;
			_tmp165_ = y;
			self->selection.height = _tmp162_ + (_tmp164_ - _tmp165_);
			_tmp166_ = y;
			self->selection.y = _tmp166_;
			break;
		}
		case CAPTURE_DRAG_STATUS_SOUTH:
		{
			gint _tmp167_ = 0;
			GdkRectangle _tmp168_ = {0};
			gint _tmp169_ = 0;
			_tmp167_ = y;
			_tmp168_ = self->selection;
			_tmp169_ = _tmp168_.y;
			self->selection.height = _tmp167_ - _tmp169_;
			break;
		}
		case CAPTURE_DRAG_STATUS_EAST:
		{
			gint _tmp170_ = 0;
			GdkRectangle _tmp171_ = {0};
			gint _tmp172_ = 0;
			_tmp170_ = x;
			_tmp171_ = self->selection;
			_tmp172_ = _tmp171_.x;
			self->selection.width = _tmp170_ - _tmp172_;
			break;
		}
		case CAPTURE_DRAG_STATUS_WEST:
		{
			gint _tmp173_ = 0;
			GdkRectangle _tmp174_ = {0};
			gint _tmp175_ = 0;
			gint _tmp176_ = 0;
			gint _tmp177_ = 0;
			_tmp173_ = self->selection.width;
			_tmp174_ = self->selection;
			_tmp175_ = _tmp174_.x;
			_tmp176_ = x;
			self->selection.width = _tmp173_ + (_tmp175_ - _tmp176_);
			_tmp177_ = x;
			self->selection.x = _tmp177_;
			break;
		}
		default:
		break;
	}
	_tmp178_ = self->priv->status;
	if (_tmp178_ != CAPTURE_DRAG_STATUS_NONE) {
		GtkDrawingArea* _tmp179_ = NULL;
		_tmp179_ = self->drawing_area;
		gtk_widget_queue_draw ((GtkWidget*) _tmp179_);
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda20__gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self) {
	gboolean result;
	result = __lambda20_ (self, event);
	return result;
}


static gboolean __lambda21_ (CaptureRegionSelect* self, GdkEventButton* context) {
	gboolean result = FALSE;
	GdkRectangle _tmp0_ = {0};
	gint _tmp1_ = 0;
	GdkRectangle _tmp8_ = {0};
	gint _tmp9_ = 0;
	GSettings* _tmp16_ = NULL;
	GdkRectangle _tmp17_ = {0};
	gint _tmp18_ = 0;
	GdkRectangle _tmp19_ = {0};
	gint _tmp20_ = 0;
	GdkRectangle _tmp21_ = {0};
	gint _tmp22_ = 0;
	GdkRectangle _tmp23_ = {0};
	gint _tmp24_ = 0;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	g_return_val_if_fail (context != NULL, FALSE);
	_tmp0_ = self->selection;
	_tmp1_ = _tmp0_.width;
	if (_tmp1_ < 0) {
		GdkRectangle _tmp2_ = {0};
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		GdkRectangle _tmp6_ = {0};
		gint _tmp7_ = 0;
		_tmp2_ = self->selection;
		_tmp3_ = _tmp2_.width;
		_tmp4_ = abs (_tmp3_);
		self->selection.width = _tmp4_;
		_tmp5_ = self->selection.x;
		_tmp6_ = self->selection;
		_tmp7_ = _tmp6_.width;
		self->selection.x = _tmp5_ - _tmp7_;
	}
	_tmp8_ = self->selection;
	_tmp9_ = _tmp8_.height;
	if (_tmp9_ < 0) {
		GdkRectangle _tmp10_ = {0};
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		GdkRectangle _tmp14_ = {0};
		gint _tmp15_ = 0;
		_tmp10_ = self->selection;
		_tmp11_ = _tmp10_.height;
		_tmp12_ = abs (_tmp11_);
		self->selection.height = _tmp12_;
		_tmp13_ = self->selection.y;
		_tmp14_ = self->selection;
		_tmp15_ = _tmp14_.height;
		self->selection.y = _tmp13_ - _tmp15_;
	}
	_tmp16_ = self->priv->settings;
	_tmp17_ = self->selection;
	_tmp18_ = _tmp17_.x;
	_tmp19_ = self->selection;
	_tmp20_ = _tmp19_.y;
	_tmp21_ = self->selection;
	_tmp22_ = _tmp21_.width;
	_tmp23_ = self->selection;
	_tmp24_ = _tmp23_.height;
	_tmp25_ = g_strdup_printf ("%d %d %d %d", _tmp18_, _tmp20_, _tmp22_, _tmp24_);
	_tmp26_ = _tmp25_;
	g_settings_set_string (_tmp16_, "selection", _tmp26_);
	_g_free0 (_tmp26_);
	self->priv->status = CAPTURE_DRAG_STATUS_NONE;
	result = TRUE;
	return result;
}


static gboolean ___lambda21__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda21_ ((CaptureRegionSelect*) self, event);
	return result;
}


static gboolean __lambda22_ (CaptureRegionSelect* self, GdkEventKey* event_key) {
	gboolean result = FALSE;
	GdkEventKey* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	g_return_val_if_fail (event_key != NULL, FALSE);
	_tmp0_ = event_key;
	_tmp1_ = _tmp0_->keyval;
	switch (_tmp1_) {
		case GDK_KEY_Up:
		{
			break;
		}
		case GDK_KEY_Right:
		{
			break;
		}
		case GDK_KEY_Down:
		{
			break;
		}
		case GDK_KEY_Left:
		{
			break;
		}
		case GDK_KEY_Return:
		{
			GSettings* _tmp2_ = NULL;
			GdkRectangle _tmp3_ = {0};
			gint _tmp4_ = 0;
			GdkRectangle _tmp5_ = {0};
			gint _tmp6_ = 0;
			GdkRectangle _tmp7_ = {0};
			gint _tmp8_ = 0;
			GdkRectangle _tmp9_ = {0};
			gint _tmp10_ = 0;
			gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			gtk_main_quit ();
			_tmp2_ = self->priv->settings;
			_tmp3_ = self->selection;
			_tmp4_ = _tmp3_.x;
			_tmp5_ = self->selection;
			_tmp6_ = _tmp5_.y;
			_tmp7_ = self->selection;
			_tmp8_ = _tmp7_.width;
			_tmp9_ = self->selection;
			_tmp10_ = _tmp9_.height;
			_tmp11_ = g_strdup_printf ("%d %d %d %d", _tmp4_, _tmp6_, _tmp8_, _tmp10_);
			_tmp12_ = _tmp11_;
			g_settings_set_string (_tmp2_, "selection", _tmp12_);
			_g_free0 (_tmp12_);
			break;
		}
		case GDK_KEY_space:
		{
			GSettings* _tmp13_ = NULL;
			GdkRectangle _tmp14_ = {0};
			gint _tmp15_ = 0;
			GdkRectangle _tmp16_ = {0};
			gint _tmp17_ = 0;
			GdkRectangle _tmp18_ = {0};
			gint _tmp19_ = 0;
			GdkRectangle _tmp20_ = {0};
			gint _tmp21_ = 0;
			gchar* _tmp22_ = NULL;
			gchar* _tmp23_ = NULL;
			gtk_main_quit ();
			_tmp13_ = self->priv->settings;
			_tmp14_ = self->selection;
			_tmp15_ = _tmp14_.x;
			_tmp16_ = self->selection;
			_tmp17_ = _tmp16_.y;
			_tmp18_ = self->selection;
			_tmp19_ = _tmp18_.width;
			_tmp20_ = self->selection;
			_tmp21_ = _tmp20_.height;
			_tmp22_ = g_strdup_printf ("%d %d %d %d", _tmp15_, _tmp17_, _tmp19_, _tmp21_);
			_tmp23_ = _tmp22_;
			g_settings_set_string (_tmp13_, "selection", _tmp23_);
			_g_free0 (_tmp23_);
			break;
		}
		case GDK_KEY_Escape:
		{
			self->priv->aborted = TRUE;
			gtk_main_quit ();
			break;
		}
		case GDK_KEY_Tab:
		{
			capture_region_select_toggle_mode (self);
			break;
		}
		default:
		{
			self->priv->aborted = TRUE;
			gtk_main_quit ();
			break;
		}
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda22__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda22_ ((CaptureRegionSelect*) self, event);
	return result;
}


CaptureRegionSelect* capture_region_select_construct (GType object_type) {
	CaptureRegionSelect * self = NULL;
	Block2Data* _data2_;
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GtkDrawingArea* _tmp4_ = NULL;
	GtkDrawingArea* _tmp5_ = NULL;
	GtkDrawingArea* _tmp6_ = NULL;
	GtkDrawingArea* _tmp7_ = NULL;
	GdkDisplay* display = NULL;
	GdkDisplay* _tmp8_ = NULL;
	GdkDisplay* _tmp9_ = NULL;
	GdkDeviceManager* _tmp10_ = NULL;
	GdkDevice* _tmp11_ = NULL;
	GdkDevice* _tmp12_ = NULL;
	GdkCursor* _tmp13_ = NULL;
	GdkCursor* _tmp14_ = NULL;
	GdkCursor* _tmp15_ = NULL;
	GdkCursor* _tmp16_ = NULL;
	GdkCursor* _tmp17_ = NULL;
	GdkCursor* _tmp18_ = NULL;
	GdkCursor* _tmp19_ = NULL;
	GdkCursor* _tmp20_ = NULL;
	GdkCursor* _tmp21_ = NULL;
	GdkCursor* _tmp22_ = NULL;
	GdkCursor** _tmp23_ = NULL;
	GdkWindow* _tmp24_ = NULL;
	GdkCursor* _tmp25_ = NULL;
	GtkDrawingArea* _tmp26_ = NULL;
	GtkDrawingArea* _tmp27_ = NULL;
	GtkDrawingArea* _tmp28_ = NULL;
	GtkWidget* _tmp29_ = NULL;
	GdkWindow* _tmp30_ = NULL;
	GdkWindow* _tmp31_ = NULL;
	GdkWindow* rootwin = NULL;
	GdkWindow* _tmp32_ = NULL;
	GdkWindow* _tmp33_ = NULL;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gint _tmp38_ = 0;
	gint _tmp39_ = 0;
	gint _tmp40_ = 0;
	gint _tmp41_ = 0;
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	self = (CaptureRegionSelect*) granite_widgets_composited_window_construct (object_type);
	_data2_->self = g_object_ref (self);
	memset (&self->selection, 0, sizeof (GdkRectangle));
	_tmp0_ = g_settings_new ("de.hannenz.capture");
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp0_;
	_tmp1_ = self->priv->settings;
	_tmp2_ = g_settings_get_string (_tmp1_, "selection");
	_tmp3_ = _tmp2_;
	sscanf (_tmp3_, "%d %d %d %d", &self->selection.x, &self->selection.y, &self->selection.width, &self->selection.height);
	_g_free0 (_tmp3_);
	self->priv->mode = CAPTURE_SELECTION_MODE_SELECTION;
	_tmp4_ = (GtkDrawingArea*) gtk_drawing_area_new ();
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->drawing_area);
	self->drawing_area = _tmp4_;
	_tmp5_ = self->drawing_area;
	g_signal_connect_object ((GtkWidget*) _tmp5_, "draw", (GCallback) _capture_region_select_on_draw_gtk_widget_draw, self, 0);
	_tmp6_ = self->drawing_area;
	gtk_widget_add_events ((GtkWidget*) _tmp6_, (gint) ((((GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK) | GDK_BUTTON1_MOTION_MASK) | GDK_BUTTON_PRESS_MASK) | GDK_BUTTON_RELEASE_MASK));
	_tmp7_ = self->drawing_area;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp7_);
	gtk_window_fullscreen ((GtkWindow*) self);
	gtk_window_set_modal ((GtkWindow*) self, TRUE);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_window_set_skip_pager_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	_tmp8_ = gdk_display_get_default ();
	_tmp9_ = _g_object_ref0 (_tmp8_);
	display = _tmp9_;
	_tmp10_ = gdk_display_get_device_manager (display);
	_tmp11_ = gdk_device_manager_get_client_pointer (_tmp10_);
	_tmp12_ = _g_object_ref0 (_tmp11_);
	_g_object_unref0 (self->mouse);
	self->mouse = _tmp12_;
	_tmp13_ = gdk_cursor_new_from_name (display, "crosshair");
	_tmp14_ = gdk_cursor_new_from_name (display, "nw-resize");
	_tmp15_ = gdk_cursor_new_from_name (display, "ne-resize");
	_tmp16_ = gdk_cursor_new_from_name (display, "se-resize");
	_tmp17_ = gdk_cursor_new_from_name (display, "sw-resize");
	_tmp18_ = gdk_cursor_new_from_name (display, "n-resize");
	_tmp19_ = gdk_cursor_new_from_name (display, "e-resize");
	_tmp20_ = gdk_cursor_new_from_name (display, "s-resize");
	_tmp21_ = gdk_cursor_new_from_name (display, "w-resize");
	_tmp22_ = gdk_cursor_new_from_name (display, "move");
	_tmp23_ = g_new0 (GdkCursor*, 10 + 1);
	_tmp23_[0] = _tmp13_;
	_tmp23_[1] = _tmp14_;
	_tmp23_[2] = _tmp15_;
	_tmp23_[3] = _tmp16_;
	_tmp23_[4] = _tmp17_;
	_tmp23_[5] = _tmp18_;
	_tmp23_[6] = _tmp19_;
	_tmp23_[7] = _tmp20_;
	_tmp23_[8] = _tmp21_;
	_tmp23_[9] = _tmp22_;
	_data2_->cursors = _tmp23_;
	_data2_->cursors_length1 = 10;
	_data2_->_cursors_size_ = _data2_->cursors_length1;
	_tmp24_ = self->gwin;
	_tmp25_ = _data2_->cursors[CAPTURE_DRAG_STATUS_NONE];
	gdk_window_set_cursor (_tmp24_, _tmp25_);
	_tmp26_ = self->drawing_area;
	g_signal_connect_object ((GtkWidget*) _tmp26_, "button-press-event", (GCallback) ___lambda19__gtk_widget_button_press_event, self, 0);
	_tmp27_ = self->drawing_area;
	g_signal_connect_data ((GtkWidget*) _tmp27_, "motion-notify-event", (GCallback) ___lambda20__gtk_widget_motion_notify_event, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	_tmp28_ = self->drawing_area;
	g_signal_connect_object ((GtkWidget*) _tmp28_, "button-release-event", (GCallback) ___lambda21__gtk_widget_button_release_event, self, 0);
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_KEY_PRESS_MASK);
	g_signal_connect_object ((GtkWidget*) self, "key-press-event", (GCallback) ___lambda22__gtk_widget_key_press_event, self, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	_tmp29_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	_tmp30_ = gtk_widget_get_window (_tmp29_);
	_tmp31_ = _g_object_ref0 (_tmp30_);
	_g_object_unref0 (self->gwin);
	self->gwin = _tmp31_;
	_tmp32_ = gdk_get_default_root_window ();
	_tmp33_ = _g_object_ref0 (_tmp32_);
	rootwin = _tmp33_;
	_tmp34_ = gdk_window_get_width (rootwin);
	_tmp35_ = gdk_window_get_height (rootwin);
	_tmp36_ = g_strdup_printf ("%ux%u", (guint) _tmp34_, (guint) _tmp35_);
	_tmp37_ = _tmp36_;
	plank_logger_notification (_tmp37_, "");
	_g_free0 (_tmp37_);
	_tmp38_ = gdk_window_get_width (rootwin);
	_tmp39_ = gdk_window_get_height (rootwin);
	gtk_window_set_default_size ((GtkWindow*) self, _tmp38_, _tmp39_);
	_tmp40_ = gdk_window_get_width (rootwin);
	_tmp41_ = gdk_window_get_height (rootwin);
	gtk_widget_set_size_request ((GtkWidget*) self, _tmp40_, _tmp41_);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	gtk_window_move ((GtkWindow*) self, 0, 0);
	_g_object_unref0 (rootwin);
	_g_object_unref0 (display);
	block2_data_unref (_data2_);
	_data2_ = NULL;
	return self;
}


CaptureRegionSelect* capture_region_select_new (void) {
	return capture_region_select_construct (CAPTURE_TYPE_REGION_SELECT);
}


GtkResponseType capture_region_select_run (CaptureRegionSelect* self) {
	GtkResponseType result = 0;
	GtkResponseType _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (self != NULL, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	gtk_window_present ((GtkWindow*) self);
	gtk_main ();
	_tmp1_ = self->priv->aborted;
	if (!_tmp1_) {
		_tmp0_ = GTK_RESPONSE_ACCEPT;
	} else {
		_tmp0_ = GTK_RESPONSE_CANCEL;
	}
	result = _tmp0_;
	return result;
}


void capture_region_select_get_selection (CaptureRegionSelect* self, GdkRectangle* result) {
	GdkRectangle _tmp0_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->selection;
	*result = _tmp0_;
	return;
}


static gboolean capture_region_select_is_near (CaptureRegionSelect* self, gint x1, gint y1, gint x2, gint y2, gint radius) {
	gboolean result = FALSE;
	gint r = 0;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = radius;
	r = _tmp0_ / 2;
	_tmp4_ = x1;
	_tmp5_ = x2;
	_tmp6_ = r;
	if (_tmp4_ >= (_tmp5_ - _tmp6_)) {
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		_tmp7_ = x1;
		_tmp8_ = x2;
		_tmp9_ = r;
		_tmp3_ = _tmp7_ <= (_tmp8_ + _tmp9_);
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		_tmp10_ = y1;
		_tmp11_ = y2;
		_tmp12_ = r;
		_tmp2_ = _tmp10_ >= (_tmp11_ - _tmp12_);
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		gint _tmp15_ = 0;
		_tmp13_ = y1;
		_tmp14_ = y2;
		_tmp15_ = r;
		_tmp1_ = _tmp13_ <= (_tmp14_ + _tmp15_);
	} else {
		_tmp1_ = FALSE;
	}
	result = _tmp1_;
	return result;
}


gboolean capture_region_select_on_draw (CaptureRegionSelect* self, cairo_t* ctx) {
	gboolean result = FALSE;
	gint width = 0;
	gint height = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	cairo_t* _tmp2_ = NULL;
	cairo_t* _tmp3_ = NULL;
	GdkRectangle _tmp4_ = {0};
	gint _tmp5_ = 0;
	cairo_t* _tmp6_ = NULL;
	cairo_t* _tmp7_ = NULL;
	GdkRectangle _tmp8_ = {0};
	gint _tmp9_ = 0;
	GdkRectangle _tmp10_ = {0};
	gint _tmp11_ = 0;
	GdkRectangle _tmp12_ = {0};
	gint _tmp13_ = 0;
	GdkRectangle _tmp14_ = {0};
	gint _tmp15_ = 0;
	cairo_t* _tmp16_ = NULL;
	cairo_t* _tmp17_ = NULL;
	GdkRectangle _tmp18_ = {0};
	gint _tmp19_ = 0;
	GdkRectangle _tmp20_ = {0};
	gint _tmp21_ = 0;
	GdkRectangle _tmp22_ = {0};
	gint _tmp23_ = 0;
	cairo_t* _tmp24_ = NULL;
	cairo_t* _tmp25_ = NULL;
	GdkRectangle _tmp26_ = {0};
	gint _tmp27_ = 0;
	GdkRectangle _tmp28_ = {0};
	gint _tmp29_ = 0;
	GdkRectangle _tmp30_ = {0};
	gint _tmp31_ = 0;
	GdkRectangle _tmp32_ = {0};
	gint _tmp33_ = 0;
	GdkRectangle _tmp34_ = {0};
	gint _tmp35_ = 0;
	GdkRectangle _tmp36_ = {0};
	gint _tmp37_ = 0;
	cairo_t* _tmp38_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (ctx != NULL, FALSE);
	gtk_window_get_size ((GtkWindow*) self, &_tmp0_, &_tmp1_);
	width = _tmp0_;
	height = _tmp1_;
	_tmp2_ = ctx;
	cairo_set_source_rgba (_tmp2_, 0.1, 0.1, 0.1, 0.8);
	_tmp3_ = ctx;
	_tmp4_ = self->selection;
	_tmp5_ = _tmp4_.y;
	cairo_rectangle (_tmp3_, (gdouble) 0, (gdouble) 0, (gdouble) width, (gdouble) _tmp5_);
	_tmp6_ = ctx;
	cairo_fill (_tmp6_);
	_tmp7_ = ctx;
	_tmp8_ = self->selection;
	_tmp9_ = _tmp8_.y;
	_tmp10_ = self->selection;
	_tmp11_ = _tmp10_.height;
	_tmp12_ = self->selection;
	_tmp13_ = _tmp12_.height;
	_tmp14_ = self->selection;
	_tmp15_ = _tmp14_.y;
	cairo_rectangle (_tmp7_, (gdouble) 0, (gdouble) (_tmp9_ + _tmp11_), (gdouble) width, (gdouble) ((height - _tmp13_) - _tmp15_));
	_tmp16_ = ctx;
	cairo_fill (_tmp16_);
	_tmp17_ = ctx;
	_tmp18_ = self->selection;
	_tmp19_ = _tmp18_.y;
	_tmp20_ = self->selection;
	_tmp21_ = _tmp20_.x;
	_tmp22_ = self->selection;
	_tmp23_ = _tmp22_.height;
	cairo_rectangle (_tmp17_, (gdouble) 0, (gdouble) _tmp19_, (gdouble) _tmp21_, (gdouble) _tmp23_);
	_tmp24_ = ctx;
	cairo_fill (_tmp24_);
	_tmp25_ = ctx;
	_tmp26_ = self->selection;
	_tmp27_ = _tmp26_.x;
	_tmp28_ = self->selection;
	_tmp29_ = _tmp28_.width;
	_tmp30_ = self->selection;
	_tmp31_ = _tmp30_.y;
	_tmp32_ = self->selection;
	_tmp33_ = _tmp32_.x;
	_tmp34_ = self->selection;
	_tmp35_ = _tmp34_.width;
	_tmp36_ = self->selection;
	_tmp37_ = _tmp36_.height;
	cairo_rectangle (_tmp25_, (gdouble) (_tmp27_ + _tmp29_), (gdouble) _tmp31_, (gdouble) ((width - _tmp33_) - _tmp35_), (gdouble) _tmp37_);
	_tmp38_ = ctx;
	cairo_fill (_tmp38_);
	result = TRUE;
	return result;
}


static void capture_region_select_toggle_mode (CaptureRegionSelect* self) {
	CaptureSelectionMode _tmp0_ = 0;
	GtkDrawingArea* _tmp21_ = NULL;
	g_return_if_fail (self != NULL);
	plank_logger_notification ("Toggling mode", "");
	_tmp0_ = self->priv->mode;
	switch (_tmp0_) {
		case CAPTURE_SELECTION_MODE_SELECTION:
		{
			GdkRectangle _tmp1_ = {0};
			gint _tmp2_ = 0;
			GdkRectangle _tmp3_ = {0};
			gint _tmp4_ = 0;
			GdkRectangle _tmp5_ = {0};
			gint _tmp6_ = 0;
			GdkRectangle _tmp7_ = {0};
			gint _tmp8_ = 0;
			GdkWindow* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			GdkWindow* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			self->priv->mode = CAPTURE_SELECTION_MODE_FULL_SCREEN;
			_tmp1_ = self->selection;
			_tmp2_ = _tmp1_.x;
			self->priv->_selection.x = _tmp2_;
			_tmp3_ = self->selection;
			_tmp4_ = _tmp3_.y;
			self->priv->_selection.y = _tmp4_;
			_tmp5_ = self->selection;
			_tmp6_ = _tmp5_.width;
			self->priv->_selection.width = _tmp6_;
			_tmp7_ = self->selection;
			_tmp8_ = _tmp7_.height;
			self->priv->_selection.height = _tmp8_;
			self->selection.x = 0;
			self->selection.y = 0;
			_tmp9_ = self->gwin;
			_tmp10_ = gdk_window_get_width (_tmp9_);
			self->selection.width = _tmp10_;
			_tmp11_ = self->gwin;
			_tmp12_ = gdk_window_get_height (_tmp11_);
			self->selection.height = _tmp12_;
			break;
		}
		case CAPTURE_SELECTION_MODE_FULL_SCREEN:
		{
			self->priv->mode = CAPTURE_SELECTION_MODE_FULL_DISPLAY;
			break;
		}
		case CAPTURE_SELECTION_MODE_FULL_DISPLAY:
		{
			GdkRectangle _tmp13_ = {0};
			gint _tmp14_ = 0;
			GdkRectangle _tmp15_ = {0};
			gint _tmp16_ = 0;
			GdkRectangle _tmp17_ = {0};
			gint _tmp18_ = 0;
			GdkRectangle _tmp19_ = {0};
			gint _tmp20_ = 0;
			self->priv->mode = CAPTURE_SELECTION_MODE_SELECTION;
			_tmp13_ = self->priv->_selection;
			_tmp14_ = _tmp13_.x;
			self->selection.x = _tmp14_;
			_tmp15_ = self->priv->_selection;
			_tmp16_ = _tmp15_.y;
			self->selection.y = _tmp16_;
			_tmp17_ = self->priv->_selection;
			_tmp18_ = _tmp17_.width;
			self->selection.width = _tmp18_;
			_tmp19_ = self->priv->_selection;
			_tmp20_ = _tmp19_.height;
			self->selection.height = _tmp20_;
			break;
		}
		default:
		break;
	}
	capture_region_select_debug_selection (self);
	_tmp21_ = self->drawing_area;
	gtk_widget_queue_draw ((GtkWidget*) _tmp21_);
}


static void capture_region_select_debug_selection (CaptureRegionSelect* self) {
	GdkRectangle _tmp0_ = {0};
	gint _tmp1_ = 0;
	GdkRectangle _tmp2_ = {0};
	gint _tmp3_ = 0;
	GdkRectangle _tmp4_ = {0};
	gint _tmp5_ = 0;
	GdkRectangle _tmp6_ = {0};
	gint _tmp7_ = 0;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->selection;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = self->selection;
	_tmp3_ = _tmp2_.y;
	_tmp4_ = self->selection;
	_tmp5_ = _tmp4_.width;
	_tmp6_ = self->selection;
	_tmp7_ = _tmp6_.height;
	_tmp8_ = g_strdup_printf ("Selection: %u|%u, %ux%u", (guint) _tmp1_, (guint) _tmp3_, (guint) _tmp5_, (guint) _tmp7_);
	_tmp9_ = _tmp8_;
	plank_logger_notification (_tmp9_, "");
	_g_free0 (_tmp9_);
}


static void capture_region_select_class_init (CaptureRegionSelectClass * klass) {
	capture_region_select_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CaptureRegionSelectPrivate));
	G_OBJECT_CLASS (klass)->finalize = capture_region_select_finalize;
}


static void capture_region_select_instance_init (CaptureRegionSelect * self) {
	self->priv = CAPTURE_REGION_SELECT_GET_PRIVATE (self);
	self->priv->aborted = FALSE;
}


static void capture_region_select_finalize (GObject* obj) {
	CaptureRegionSelect * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CAPTURE_TYPE_REGION_SELECT, CaptureRegionSelect);
	_g_object_unref0 (self->drawing_area);
	_g_object_unref0 (self->mouse);
	_g_object_unref0 (self->gwin);
	_g_object_unref0 (self->priv->settings);
	G_OBJECT_CLASS (capture_region_select_parent_class)->finalize (obj);
}


GType capture_region_select_get_type (void) {
	static volatile gsize capture_region_select_type_id__volatile = 0;
	if (g_once_init_enter (&capture_region_select_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CaptureRegionSelectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) capture_region_select_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaptureRegionSelect), 0, (GInstanceInitFunc) capture_region_select_instance_init, NULL };
		GType capture_region_select_type_id;
		capture_region_select_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, "CaptureRegionSelect", &g_define_type_info, 0);
		g_once_init_leave (&capture_region_select_type_id__volatile, capture_region_select_type_id);
	}
	return capture_region_select_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



